# PDD revision lessons, Units 1-5.
# st: "EX" = existing lesson used as-is (reordered), "EDIT" = existing + light edit, "NEW" = new lesson stub.
LESSONS_A = [
# ---------------- UNIT 1 ----------------
dict(n="1.1", title="Intro to Digital Photography", st="EX", ex=["EX02"],
 acp=["1.3.a"], comp=["K1", "K2", "K3"],
 source="Existing: Adobe edex \"Understanding Digital Photography\" lesson plan + the Photography Basics deck (in the FDD folder). Reordered to open the course. Replaces the empty processes/pdd1/1_1.md stub.",
 drive=["Understanding digital photography (Adobe edex lesson plan)", "Photography Basics (slides)"],
 di_note="\"I Do\": how a digital camera makes an image (lens, sensor, pixels), camera types, the parts of a DSLR",
 gp_note="\"We Do\": camera parts scavenger hunt with a partner, then 10 practice frames in Auto",
 target="identify the parts of a DSLR and explain how light becomes a digital image (sensor, pixel, resolution) by labeling a camera diagram and taking 10 practice frames",
 org="A labeled DSLR diagram handout is the reference for every camera day this unit.",
 conn="Starts from the photos students already scroll past every day, then asks how a camera actually captures one.",
 collab="Partners split one camera: one reads the diagram, the other finds each part on the body, then they switch.",
 evid="The completed camera-parts diagram plus 10 practice frames on the card.",
 summ="Exit ticket: rate confidence on handling the camera, with one specific question for tomorrow's manual-mode lesson.",
 binder=["your labeled DSLR diagram"], files=[], plus="every part labeled correctly with a one-word job for each", minus="diagram incomplete or no practice frames on the card",
 iep="Pre-labeled diagram with a word bank; pair with a peer who reads the steps aloud.",
 ell="Picture vocabulary bank (lens, sensor, shutter, mode dial) with photos of the actual school cameras.",
 gt="Compare the DSLR to a phone camera: list three things the DSLR can control that the phone hides.",
 mats=["Canon Rebel DSLRs (one per pair), charged batteries, formatted SD cards", "Camera-parts diagram handout", "Photography Basics deck"],
 notes="No GMetrix in Unit 1 (same as FDD and ADD): the lab setup and pre-test land in 2.1. The guided-practice block runs long on camera days so cameras go out and come back once per period.",
 intro="This year you'll learn to make photographs on purpose instead of by accident. It starts with knowing your camera.",
 di="A camera is a dark box that lets light in for a controlled moment. The **lens** focuses the light, the **shutter** decides how long it comes in, and the **sensor** records it as millions of **pixels**. The more pixels, the higher the **resolution**. Today you'll learn where each of those lives on our cameras.",
 cue="Every photo you've ever taken was a decision about light. This year you make that decision instead of the phone.",
 q=("Which part of the camera records the light?", "Why might a photographer choose a DSLR over a phone for a sports game?", "If a sensor has more pixels but is the same size, what might that change about the photo?"),
 gp=["**Camera parts hunt:** with your partner, find every part on the diagram on the actual camera body. Point and name it out loud.",
     "**Turn and Talk:** which three parts do you think you'll touch most? Why?",
     "**Practice frames:** set the mode dial to Auto and take 10 frames around the room: 3 close, 3 medium, 3 wide, and 1 of your choice.",
     "**Check your card:** review the frames on the LCD screen. Star your best one."],
 disc="What surprised you about how many controls the camera has? Which one do you most want to learn first?",
 refl="Which part of the camera did you understand least today, and what's your question about it?",
 track="Start a SkillsUSA written-test flashcard deck: one card per camera part, term on the front, job on the back."),

dict(n="1.2", title="Manual Modes & the Exposure Triangle", st="EX", ex=["EX03"],
 acp=["1.4.a"], comp=["K2", "K3", "K10", "T11"],
 source="Existing: Manual Photography lesson and the CameraSim handout. Unchanged; reordered to day 2.",
 drive=["Manual Photography (CameraSim handout)"],
 di_note="\"I Do\": aperture, shutter speed, ISO; what each does to exposure and to the look of the photo; the light meter in the viewfinder",
 gp_note="\"We Do\": CameraSim challenges, then real cameras in M mode: hit a correct exposure three different ways",
 target="explain how aperture, shutter speed, and ISO each change exposure by setting a correct manual exposure three different ways and recording each setting",
 org="The CameraSim handout sequences the three settings one at a time before combining them.",
 conn="Picks up yesterday's parts diagram: the aperture is inside the lens, the shutter is in front of the sensor, ISO is the sensor's sensitivity.",
 collab="Think-Pair-Share comparing three exposures of the same subject; partners swap who sets the camera and who records the settings.",
 evid="A settings log with three correctly exposed frames of the same subject, each made with a different combination.",
 summ="Glow & Grow on which setting was easiest and hardest to control.",
 binder=["your CameraSim handout", "your settings log"], files=[], plus="all three exposures are correct and the log names the trade-off each one made", minus="fewer than three frames, or the settings aren't recorded",
 iep="Exposure triangle graphic organizer with arrows showing 'more light / less light' for each setting.",
 ell="Sentence frame: 'I changed ___ from ___ to ___, so the photo got ___.'",
 gt="Make the same exposure two more ways with the most extreme settings possible and explain what each one costs (blur, noise, or depth of field).",
 mats=["CameraSim (camerasim.com) on lab computers", "DSLRs in M mode", "Settings log handout"],
 notes="The settings log introduced today is used all year; it becomes the metadata in each TSA image statement (camera, f-stop, exposure time, ISO, focal length).",
 intro="Auto mode guesses. Manual mode lets you decide. Today you take control of exposure.",
 di="Exposure is how much light reaches the sensor. Three settings control it. **Aperture** (f-number) is the size of the opening; a small f-number like f/4 is a big opening. **Shutter speed** is how long it stays open; 1/1000 freezes action, 1/15 blurs it. **ISO** is how sensitive the sensor is; higher ISO is brighter but grainier. Each full step, called a **stop**, doubles or halves the light.",
 cue="Watch the light meter in the viewfinder. When the needle sits on zero, the camera thinks this exposure is correct. Now I can get to zero three different ways.",
 q=("Which f-number lets in more light: f/4 or f/11?", "Why would a sports photographer raise ISO instead of slowing the shutter?", "If you need both a fast shutter and lots of depth of field in a dim gym, what has to give, and why?"),
 gp=["**CameraSim warm-up:** complete the handout's three challenges (freeze the windmill, blur the windmill, keep the background sharp).",
     "**Switch to M:** set ISO 400 and center the light meter on one subject using aperture and shutter.",
     "**Three ways to zero:** make two more correct exposures of the same subject with different combinations. Record each in your settings log.",
     "**Think-Pair-Share:** compare your three frames with your partner. Which looks different, even though they're all 'correct'?"],
 disc="Why can two photos with the same exposure look completely different?",
 refl="Which of the three settings was hardest to control today, and what would you practice next?",
 track="Add aperture, shutter speed, ISO, and stop to the flashcard deck, each with a one-line example."),

dict(n="1.3", title="Focal Length, Crop Factor & Depth of Field", st="EX", ex=["EX08"],
 acp=["1.4.a"], comp=["K2", "K3"],
 source="Existing: Focal Length / Sensor / Crop Factor deck (written for the Canon T6 Rebel). Unchanged; reordered to day 3.",
 drive=["Focal Length, Sensor & Crop Factor (slides)"],
 di_note="\"I Do\": focal length and field of view, crop factor on APS-C sensors, depth of field and what controls it",
 gp_note="\"We Do\": zoom walk (same subject at 18 mm and 55 mm), then a depth-of-field series at f/5.6 and f/22",
 target="predict how focal length, crop factor, and aperture change field of view and depth of field by shooting a labeled zoom pair and an aperture pair of one subject",
 org="Students shoot in labeled pairs so every comparison is side by side.",
 conn="Builds on 1.2's aperture: now aperture also changes how much of the scene is sharp, not just how bright it is.",
 collab="Partners predict out loud before each shot, then check the LCD together.",
 evid="Two labeled pairs (zoom pair, aperture pair) shown to the teacher on the camera's LCD or uploaded.",
 summ="Emoji meter on predicting depth of field.",
 binder=["your settings log, with today's pairs added"], files=[], plus="both pairs show a clear difference and the log explains why", minus="pairs missing or not labeled",
 iep="Provide a pre-filled prediction chart (wide/tele, shallow/deep) to circle before each shot.",
 ell="Visual cards: wide angle, telephoto, shallow, deep, each with an example photo.",
 gt="Calculate the full-frame equivalent of every focal length on the kit lens and explain why a 'portrait lens' on a full-frame camera behaves differently on ours.",
 mats=["DSLRs with 18–55 mm kit lenses", "Focal Length deck", "A colorful subject (toy or plant) per table"],
 notes="Canon APS-C crop factor is about 1.6 (the deck uses 1.62).",
 intro="Zoom changes more than how big your subject looks. Today you'll see how lens and aperture shape the whole picture.",
 di="**Focal length** (in mm) sets the **field of view**: 18 mm is wide, 55 mm is tighter. Our cameras have a smaller sensor than full-frame, so they crop the view by about **1.6×**: a 50 mm lens looks like 80 mm would on a full-frame camera. **Depth of field** is how much of the scene is in focus. A wide aperture (small f-number), a longer focal length, and a closer subject all make it shallower.",
 cue="I'm going to blur this background without touching Photoshop. Watch: f/5.6, zoom in, step closer.",
 q=("What does a shorter focal length do to the field of view?", "Why does a portrait at 55 mm often look more flattering than one at 18 mm up close?", "You need a whole team photo sharp, front row to back. Which three settings would you choose, and why?"),
 gp=["**Zoom pair:** photograph the same subject at 18 mm and at 55 mm, moving your feet so it fills the frame both times.",
     "**Aperture pair:** in Av or M, photograph a subject with a background at f/5.6 and at f/22.",
     "**Turn and Talk:** before checking the LCD, predict which frame has the blurrier background. Then check.",
     "**Log it:** add both pairs to your settings log with focal length and f-number."],
 disc="When would you want a deep depth of field instead of a blurry background?",
 refl="How confident are you predicting depth of field before you take the shot? Explain with one of today's pairs.",
 track="Crop-factor practice: convert 18, 35, and 55 mm to full-frame equivalents for the flashcard deck."),

dict(n="1.4", title="Composition", st="EDIT", ex=["EX09"],
 acp=["1.4.a"], comp=["T12", "K4"],
 source="Existing: the Composition decks. Light edit: the two composition lessons in the 2023 outline (Unit 1 and Unit 4) are merged into this one lesson, and aspect ratio is added because it is named in ACP 1.4.a. Framing (EX07) is taught again in 3.1 for photojournalism.",
 drive=["Composition (slides)"],
 di_note="\"I Do\": rule of thirds, leading lines, framing, viewpoint, negative space, aspect ratio",
 gp_note="\"We Do\": composition scavenger hunt: one frame per technique around campus",
 target="apply rule of thirds, leading lines, framing, viewpoint, and negative space by shooting one deliberate example of each and labeling the technique",
 org="A six-box scavenger-hunt card lists each technique with a thumbnail sketch.",
 conn="Uses 1.3's focal length and depth of field as composition tools, not just settings.",
 collab="Teams of two hunt together; a gallery walk at the end lets pairs guess each other's techniques.",
 evid="Six labeled frames, one per technique.",
 summ="3-2-1 on today's techniques.",
 binder=["your scavenger-hunt card"], files=[], plus="every technique is clearly shown and correctly labeled", minus="fewer than four techniques shown",
 iep="Reduce the hunt to four techniques; provide example photos on the card.",
 ell="Card shows each technique as a diagram plus a sample photo.",
 gt="Break a rule on purpose in one extra frame and explain why it works.",
 mats=["DSLRs", "Composition deck", "Scavenger-hunt card"],
 notes="Campus shooting needs a hall-pass routine; the hall-pass teacher tool works for pairs.",
 intro="A good photo guides the eye. Today you'll practice six ways to do it.",
 di="**Rule of thirds** places the subject on the grid lines, not dead center. **Leading lines** pull the eye toward the subject. **Framing** surrounds the subject with something in the scene (a doorway, branches). **Viewpoint** changes the story: shoot low to make a subject powerful, high to make it small. **Negative space** gives the subject room. **Aspect ratio** is the shape of the frame: our cameras shoot 3:2; Instagram prefers 4:5.",
 cue="Turn on the grid in Live View. I put her eye on this intersection, not in the middle, and now the photo has somewhere to go.",
 q=("What is the rule of thirds?", "Why does a low viewpoint make a subject look more powerful?", "Pick one technique you'd use to make a lonely-looking photo. Explain your choice."),
 gp=["**Turn on the grid** in Live View (Menu → Grid display).",
     "**Scavenger hunt:** shoot one frame for each technique: rule of thirds, leading lines, framing, low viewpoint, high viewpoint, negative space.",
     "**Gallery walk:** show your six frames to another pair. They guess the technique before you tell them.",
     "**Pick your best** and write one sentence on why it works."],
 disc="Which technique made the biggest difference to your photos today?",
 refl="Write 3 things you shot, 2 techniques and how you used them, and 1 question you still have.",
 track="Tag your strongest composition frame as a possible TSA student-choice image in your settings log."),

# ---------------- UNIT 2 ----------------
dict(n="2.1", title="GMetrix Setup & ACP Pre-Test", st="NEW", ex=[],
 acp=[], comp=[], et="pdd2-1-score", special="pretest",
 source="NEW. A port of FDD 2.1 and ADD 2.1 with Photoshop in place of Illustrator/Premiere Pro. The existing PDD course has no GMetrix day; this gives students the same baseline the other two courses get before BrainBuffet Module 1.",
 drive=[],
 target="log in to GMetrix SMS with their school Google account and complete the Adobe Photoshop practice exam, establishing a baseline before Module 1 instruction begins",
 org="The numbered steps (log in, pre-launch setup, launch the exam, screenshot) follow the exact order students click.",
 conn="Unit 1 had no Photoshop, so this is the first time students touch the platform; a baseline before training starts shows each student where Module 1 needs to take them.",
 collab="Quietly help a neighbor stuck logging in or launching the exam; the pre-test itself is solo.",
 evid="A screenshot of the pre-test results screen.",
 summ="Custom exit ticket: post the score, the screenshot, and a reflection on the most unfamiliar part of the exam.",
 binder=[], files=[("your GMetrix pre-test results screenshot", "Screenshots")], plus="the screenshot clearly shows a completed pre-test with a score", minus="no screenshot, or it doesn't show a score",
 iep="Printed step checklist to check off one at a time; extra time on the pre-test.",
 ell="GMetrix interface language set to the student's home language for login and navigation, if testing rules allow.",
 gt="Once finished, preview Module 1's topic list and note the section you're most looking forward to.",
 mats=["GMetrix SMS and Adobe Photoshop (26.11, run in Rosetta) on every lab Mac", "Each student's school Google account", "The class GMetrix code (Schoology homepage)", "Lab administrator password (teacher enters it at each machine during pre-launch)"],
 notes="Files are deployed by hand (no Jamf), so before this day copy any GMetrix Photoshop practice files to /Users/Shared/GMetrix on all 24 Macs and check that Photoshop opens in Rosetta. Photoshop must stay at or below 26.11 for the GMetrix plugin (see Notes for IT). Pre-launch setup has to be redone at every new log-on, and each GMetrix task prompts for the admin password, so start it as soon as the first students are logged in.",
 intro="Today is different from every other day this year. No new Photoshop content: you'll get into GMetrix, the practice platform for the rest of the course, and find out where you're starting from."),

dict(n="2.2", title="Workspace, Documents & Navigation", st="EDIT", ex=["EX01"],
 acp=["2.1.a", "2.1.b", "2.2.a", "2.2.b", "2.2.c", "2.2.d"], comp=["K9"],
 source="Existing: Welcome Back Graphic. Light edit: the project is now the vehicle for document setup and navigation, with three added mini-demos the existing lesson didn't name: saving a document preset (2.1.b), preferences (2.2.b), and Hand/Zoom/Rotate View plus rulers, guides, and grids (2.2.c–d).",
 drive=["Welcome Back Graphic (exemplar folder)"],
 di_note="\"I Do\": New Document dialog (size, resolution, color mode), saving a preset, the workspace and panels, preferences, Hand/Zoom/Rotate View, rulers/guides/grids",
 gp_note="\"We Do\": build the Welcome Back Graphic on a saved preset with guides",
 target="create a correctly sized document, save it as a preset, and navigate with Hand, Zoom, Rotate View, rulers, and guides by building the Welcome Back Graphic",
 org="A setup checklist (size, resolution, color mode, preset name) is completed before anything is placed.",
 conn="Connects Unit 1's resolution vocabulary to the New Document dialog: pixels are now a setting you choose.",
 collab="Turn and Talk on which navigation shortcut they will use most; partners check each other's document settings against the checklist.",
 evid="Screenshot Receipt: the New Document dialog showing the saved preset, plus the graphic with guides visible.",
 summ="Glow & Grow on the first Photoshop day.",
 binder=["your setup checklist"], files=[("your Welcome Back Graphic .psd", "Project Files"), ("your preset screenshot", "Screenshots")], plus="the preset is named and reused, and guides are placed by number, not by eye", minus="no preset, or the document settings don't match the checklist",
 iep="Screenshot-annotated setup checklist; keyboard shortcut card for Hand (Space), Zoom (Z), and Rotate View (R).",
 ell="Interface labels shown in a picture glossary (panel, toolbar, Options bar, preset).",
 gt="Create a custom workspace for photo editing, save it, and explain the three panels you kept.",
 mats=["Photoshop on lab Macs", "Welcome Back Graphic exemplar", "Setup checklist"],
 notes="BrainBuffet Module 1 begins in today's strand.",
 intro="Before you edit a single photo, set up the file right. Today you'll build your Welcome Back Graphic and learn to get around Photoshop.",
 di="Every Photoshop file starts in **File → New**. Choose the size in pixels or inches, the **resolution** (300 ppi for print, 72 is fine for screens), and the **color mode** (RGB for screens, CMYK for print). Save the settings as a **preset** so you never set them up twice. Then learn to move around: **Hand** (hold Space), **Zoom** (Z), **Rotate View** (R), and **rulers** (⌘R) with **guides** dragged from them. **Preferences** (Photoshop → Settings) control things like units and the number of undos.",
 cue="I don't eyeball my margins. View → Guides → New Guide Layout, type the number, and it's exact.",
 q=("What color mode would you use for a printed poster?", "Why save a preset instead of typing the settings each time?", "Design the preset you'd want for a yearbook spread. What settings, and why?"),
 gp=["**New document:** 8 × 10 in, 300 ppi, RGB. Save it as a preset named 'PDD 8x10 Print'.",
     "**Rulers and guides:** turn on rulers, set units to inches in Preferences, and add a 0.5 in margin with New Guide Layout.",
     "**Build the graphic:** place your name and one image into the Welcome Back layout.",
     "**Navigate:** zoom to 300%, pan with Space, rotate the view 15°, then reset it (Esc). Show your partner."],
 disc="Which navigation shortcut do you think you'll use most? Why?",
 refl="Write one Glow and one Grow from your first day in Photoshop.",
 track="Two-minute drill: set up a 1080 × 1350 px Instagram document from memory."),

dict(n="2.3", title="Layer Basics", st="EX", ex=["EX40"],
 acp=["3.1.a", "3.1.b", "5.3.b"], comp=["K9"],
 source="Existing: Didact Layer Basics (Classroom in a Book Lesson 4). Unchanged.",
 drive=["Layer Basics (Didact / CIB Lesson 4)"],
 di_note="\"I Do\": the Layers panel; create, name, group, reorder, lock; opacity vs fill; blend modes; Free Transform",
 gp_note="\"We Do\": Classroom in a Book Layer Basics project",
 target="create, name, group, reorder, and transform layers, and set opacity, fill, and blend mode, by completing the Layer Basics project with a named, organized Layers panel",
 org="The tutorial's numbered steps; a 'named layers' requirement makes the panel itself the evidence.",
 conn="Builds on 2.2's document: now the document has parts you can change separately.",
 collab="Step-checking partners: one reads the step, the other checks the screen, swap every section.",
 evid="Screenshot Receipt: the Layers panel with every layer named and at least one group.",
 summ="Emoji meter on layers.",
 binder=[], files=[("your Layer Basics .psd", "Project Files"), ("your Layers panel screenshot", "Screenshots")], plus="every layer is named, grouped logically, and stacked correctly", minus="layers left as 'Layer 1, Layer 2'",
 iep="Chunk the tutorial into three checkpoints with a teacher check at each.",
 ell="Layers panel diagram with each icon labeled in English and the home language.",
 gt="Explain the difference between Opacity and Fill using a layer style, and show both.",
 mats=["Photoshop", "CIB Lesson 4 files (copied to each Mac or Drive)"],
 notes="Practice files are copied by hand to each Mac (no Jamf); keep a master copy in the shared Drive folder.",
 intro="Layers are why Photoshop edits can be undone and changed later. Today you'll organize a project the way professionals do.",
 di="Each **layer** is a separate sheet. Name every layer (double-click its name), **group** related layers (⌘G), and drag to change the stacking order. **Opacity** fades everything on a layer; **Fill** fades the pixels but not the layer style. **Blend modes** change how a layer mixes with the ones below. **Free Transform** (⌘T) scales and rotates.",
 cue="If I can't find a layer in three seconds, my file isn't organized yet.",
 q=("How do you rename a layer?", "When would you lower Fill instead of Opacity?", "Plan the layer structure for a magazine cover. What groups would you make?"),
 gp=["**Open** the Layer Basics start file and save a copy as yourname-layers.psd.",
     "**Follow the tutorial** steps with your step-checking partner.",
     "**Name and group** every layer as you go.",
     "**Turn and Talk:** show your partner one blend mode and explain what it did."],
 disc="Why does organized layering matter more on a team project?",
 refl="How confident are you with layers? Name one thing you could do and one you'd want to review.",
 track="Two-minute drill: group four layers and change a blend mode without the tutorial."),

dict(n="2.4", title="Selection Tools", st="NEW", ex=[],
 acp=["5.1.a", "5.1.b"], comp=["K9"],
 source="NEW. No existing PDD lesson teaches the selection tools directly, but ACP 5.1.a names them all (marquee, lasso, Quick Selection, Magic Wand, Object Selection, Select Subject/Sky, Selection Brush, Color Range). Built on Classroom in a Book's selections chapter, which is already in the Drive Photoshop folder.",
 drive=["Classroom in a Book 2023 PDF (selections chapter)"],
 di_note="\"I Do\": marquee and lasso, Quick Selection, Magic Wand, Object Selection, Select Subject and Select Sky, Color Range, adding/subtracting, a first look at Select and Mask",
 gp_note="\"We Do\": selection challenge: five subjects, five tools",
 target="choose the right selection tool for a subject and refine its edge by isolating five practice subjects with five different tools",
 org="A five-row challenge sheet pairs each subject with a suggested tool.",
 conn="Uses 2.3's layers: each selection goes onto its own named layer.",
 collab="Think-Pair-Share: partners argue for which tool fits each subject before trying it.",
 evid="Screenshot Receipt of the Layers panel with five isolated subjects on named layers.",
 summ="3-2-1 on selection tools.",
 binder=["your selection challenge sheet"], files=[("your selection challenge .psd", "Project Files")], plus="edges are clean and the tool used is logged for each subject", minus="fewer than three subjects isolated",
 iep="Start with three subjects and the tool pre-chosen; provide a shortcut card (Shift = add, Option = subtract).",
 ell="Tool icons with names and one-word use (shape, color, edge, AI).",
 gt="Isolate hair against a busy background with Select and Mask, and explain each setting you changed.",
 mats=["Photoshop", "Selection challenge start file (five subjects)", "Challenge sheet"],
 notes="Stub: the start file still needs to be assembled (five subjects: a geometric object, a solid-color sky, a person, an object on a busy table, a single-color shirt). Unit 6 returns to Select and Mask in depth.",
 intro="Almost every edit starts with a selection. Today you'll learn which tool to grab for which job.",
 di="Geometric shapes: **Marquee**. Freehand: **Lasso** and **Polygonal Lasso**. Clear edges: **Quick Selection** or **Object Selection**. A whole person: **Select → Subject**. A sky: **Select → Sky**. One color: **Magic Wand** or **Color Range**. Hold **Shift** to add and **Option** to subtract. Click **Select and Mask** to clean up the edge.",
 cue="The best selection tool is the one that does the most work for me. For a person, I try Select Subject first, then fix what it missed.",
 q=("Which tool selects everything of one color?", "Why might Select Subject fail on a photo of a person in front of a crowd?", "Plan the fastest way to select a blue car in a parking lot full of cars. Which tools, in what order?"),
 gp=["**Open** the challenge file. Each subject is on the Background layer.",
     "**Think-Pair-Share:** pick a tool for each subject before trying.",
     "**Select and copy** each subject to its own layer (⌘J), named for the tool you used.",
     "**Refine one edge** in Select and Mask and compare with your partner."],
 disc="Which subject was hardest to select, and what tool finally worked?",
 refl="Write 3 things you selected, 2 tools and when to use them, and 1 question.",
 track="SkillsUSA K9 practice: select and replace the background on one Unit 1 portrait in 15 minutes."),
]
