# PDD revision lessons, Units 6-9.
LESSONS_C = [
# ---------------- UNIT 6 ----------------
dict(n="6.1", title="Masks & Channels", st="EX", ex=["EX28"],
 acp=["3.2.a", "3.2.b", "5.1.b", "5.1.c"], comp=["K9"],
 source="Existing: Didact Lesson06 Masks & Channels (Classroom in a Book). Unchanged.",
 drive=["Lesson06 Masks & Channels (Didact)"],
 bell="The eraser and a layer mask can both hide part of a photo. Why do professionals almost never use the eraser?",
 di_note="\"I Do\": layer masks (black hides, white reveals), Select and Mask, saving and loading selections, alpha channels",
 gp_note="\"We Do\": Masks & Channels tutorial",
 target="hide and reveal with layer masks, refine edges with Select and Mask, and save and load selections as channels by completing the Masks & Channels project",
 org="'Black conceals, white reveals' card at every station.",
 conn="2.4's selections become masks, which stay editable.",
 collab="Step-checking partners.",
 evid="Screenshot Receipt: the Layers panel with a mask and the Channels panel with a saved alpha channel.",
 summ="Stoplight.",
 binder=[], files=[("your masks .psd", "Project Files")], plus="mask edges are refined and a selection is saved to a named channel", minus="the eraser was used, or no saved channel",
 iep="Tutorial chunked into three checkpoints.",
 ell="Mask color card: black = hide, white = show, gray = partial.",
 gt="Use a channel to select hair against sky (calculations or channel contrast).",
 mats=["Photoshop", "Lesson06 files"], notes="",
 intro="Masks are the most important skill in Photoshop. They let you hide anything without throwing it away.",
 di="A **layer mask** hides parts of a layer: paint **black** to hide, **white** to reveal, gray for partly. **Select and Mask** refines tricky edges like hair. Save a selection (**Select → Save Selection**) and it becomes an **alpha channel** you can reload any time.",
 cue="I hid too much. No problem: switch to white and paint it back.",
 q=("What does black do on a layer mask?", "Why is a mask better than the eraser?", "How could a saved channel help on a project you return to next week?"),
 gp=["**Open** the Lesson06 start file.", "**Follow the tutorial** with your step partner.", "**Save a selection** as a named channel.", "**Turn and Talk:** show a mask edit you could undo."],
 disc="What would you mask in one of your own photos?",
 refl="Stoplight on masks, with one specific question.",
 track="TSA: re-edit one candidate image with masks only, and log it."),

dict(n="6.2", title="Double Exposure", st="EX", ex=["EX16"],
 acp=["3.1.b", "3.2.a", "3.2.e"], comp=["K8"],
 source="Existing: Double Exposure (exemplar folder). Moved from the art-photography unit of the 2023 outline to follow masks, because it depends on masks, blend modes, and clipping masks.",
 drive=["Double Exposure (exemplars)"],
 bell="Look at this double exposure. Which two images do you see, and how do they relate?",
 di_note="\"I Do\": Select Subject to mask a portrait, Screen and Lighten blend modes, clipping masks, Paste Into",
 gp_note="\"We Do\": build a double exposure from your own portrait and a landscape",
 target="blend two photos into a double exposure using masks, blend modes, and a clipping mask",
 org="Exemplar board with three sample double exposures and their layer stacks.",
 conn="Applies 6.1's masks and 2.3's blend modes together.",
 collab="Gallery walk: partners name the two images and the idea connecting them.",
 evid="Glow & Grow with a screenshot of the layer stack.",
 summ="Glow & Grow.",
 binder=[], files=[("your double exposure", "Project Files")], plus="the two images connect in meaning, not just visually", minus="no clipping mask or blend mode used",
 iep="Provide a matched portrait/landscape pair.",
 ell="Sentence frame for the gallery walk: 'I see ___ and ___. Together they show ___.'",
 gt="Build a triple exposure with a gradient mask transition.",
 mats=["Photoshop", "Double Exposure exemplars", "Students' Unit 4 portraits"], notes="",
 intro="A double exposure puts two photos in one frame so they tell one story.",
 di="Select the subject and mask it. Place the second image above it and **clip** it (Option-click between layers) so it shows only inside the subject. Change the **blend mode** to Screen or Lighten so the portrait's shadows let the landscape through. **Paste Into** (Edit → Paste Special) is another way to put an image inside a selection.",
 cue="Option-click the line between layers. The forest only exists inside her silhouette now.",
 q=("What does a clipping mask do?", "Why does Screen blend mode work well here?", "Which landscape would tell the strongest story with your portrait?"),
 gp=["**Mask your portrait** with Select Subject.", "**Clip a landscape** to it.", "**Try three blend modes** and keep the best.", "**Gallery walk** with a partner."],
 disc="What makes a double exposure meaningful instead of just interesting?",
 refl="Glow and Grow on your double exposure.",
 track="SkillsUSA K8 warm-up: a two-image composite with a clear theme."),

dict(n="6.3", title="Patterns, Gradients & Swatches", st="EDIT", ex=["EX29"],
 acp=["2.4.a", "2.4.b", "2.4.c", "2.5.a", "2.5.b"], comp=[],
 source="Existing: Didact Lesson06 Pattern. Light edit: adds gradients, swatches, and exporting swatches as an ASE file, plus saving to Libraries (ACP 2.4–2.5, not covered anywhere in the existing course).",
 drive=["Lesson06 Pattern (Didact)"],
 bell="Find a pattern in the room. What's the smallest piece that repeats?",
 di_note="\"I Do\": Color Picker and Eyedropper, Swatches panel and ASE export, Gradient tool and presets, defining a pattern, Libraries",
 gp_note="\"We Do\": define a pattern from a photo, sample a palette into swatches, save a gradient",
 target="build and save a pattern, a gradient, and a swatch group, and export the swatches as ASE",
 org="A three-part checklist: pattern, gradient, swatches.",
 conn="Unit 4's color temperature returns: palettes pulled from student photos.",
 collab="Partners trade ASE files and load each other's palettes.",
 evid="Two-Minute Drill: build a two-color gradient from swatches on command; screenshot.",
 summ="Emoji meter.",
 binder=[], files=[("your swatches .ase", "Project Files")], plus="the swatch group is named and the gradient is saved as a preset", minus="no saved swatches or pattern",
 iep="Checklist with screenshots of each panel.",
 ell="Panel diagrams labeled.",
 gt="Create a seamless pattern with Offset filter and explain why it tiles.",
 mats=["Photoshop", "Lesson06 Pattern files"], notes="",
 intro="Color and patterns you build once can be reused forever. Today you'll build a kit.",
 di="Sample colors with the **Eyedropper** and add them to the **Swatches** panel in a named group. Export swatches as an **ASE** file to share with other Adobe apps. The **Gradient tool** blends colors; save your own as a preset. **Edit → Define Pattern** turns a selection into a repeating fill. **Libraries** store all of these in the cloud.",
 cue="Eyedropper, sample, new swatch. Do it five times and I have a palette straight from my photo.",
 q=("What does an ASE file store?", "Why save a gradient as a preset?", "Build a palette for a brand from one of your photos. Which five colors, and why?"),
 gp=["**Sample five colors** from one of your photos into a named swatch group.", "**Export** the group as ASE.", "**Build and save a gradient** from two swatches.", "**Define a pattern** and fill a layer with it."],
 disc="How could a photographer use a palette from their photos in their portfolio design?",
 refl="Emoji meter on swatches and gradients.",
 track="Use your photo palette in your TSA portfolio's title page."),

dict(n="6.4", title="Typographic Design", st="EDIT", ex=["EX30"],
 acp=["1.4.b", "4.3.a", "4.3.b", "4.3.c"], comp=[],
 source="Existing: Didact Lesson07 Typographic Design 1 & 2, merged into one period with the Paragraphs lesson from the 2023 outline. Light edit: adds Type on a Path, Warp Text, Check Spelling, and Rasterize/Convert to Shape (ACP 4.3.a and 4.3.c).",
 drive=["Lesson07 Typographic Design 1 & 2 (Didact)"],
 bell="Look at a magazine cover. What do you read first, second, third? Why?",
 di_note="\"I Do\": typographic hierarchy; point and paragraph type; Character and Paragraph panels; Type on a Path; Warp Text; spelling; rasterize vs convert to shape",
 gp_note="\"We Do\": Lesson07 typographic design project",
 target="set type with a clear hierarchy using the Character and Paragraph panels, and use Type on a Path, Warp Text, and Check Spelling",
 org="A hierarchy diagram: headline, deck, body, caption.",
 conn="Prepares directly for S6's magazine cover.",
 collab="Partners rank each other's type layers by reading order.",
 evid="3-2-1.",
 summ="3-2-1.",
 binder=["your hierarchy diagram"], files=[("your typography .psd", "Project Files")], plus="hierarchy reads clearly in the intended order and type stays live", minus="type was rasterized unnecessarily or spelling errors remain",
 iep="Hierarchy template with sizes pre-filled.",
 ell="Type vocabulary cards with visual examples (kerning, tracking, leading).",
 gt="Set a pull quote on a path that follows a curve in the photo.",
 mats=["Photoshop", "Lesson07 files"], notes="",
 intro="Type tells the reader where to look. Today you'll control it.",
 di="**Hierarchy** is the order the eye reads: size, weight, color, and position decide it. **Point type** is for short lines; **paragraph type** flows in a box. The **Character** panel controls font, size, **kerning**, **tracking**, and **leading**; the **Paragraph** panel controls alignment and spacing. Type can follow a path or be warped. Keep it live; **rasterize** only when you must.",
 cue="Headline 72 pt, deck 24 pt, body 11 pt. The size jumps do the work.",
 q=("What's the difference between kerning and tracking?", "Why keep type live instead of rasterizing?", "Design the hierarchy for an event poster with five pieces of information."),
 gp=["**Complete** the Lesson07 project.", "**Add Type on a Path** to one element.", "**Run Check Spelling.**", "**Turn and Talk:** rank your partner's hierarchy."],
 disc="What makes a type choice feel right for a photo?",
 refl="3-2-1 on type.",
 track=""),

# ---------------- UNIT 7 ----------------
dict(n="7.1", title="Monster Maker: Smart Objects & Puppet Warp", st="EDIT", ex=["EX32"],
 acp=["3.1.c", "5.3.b"], comp=["K8"],
 source="Existing: Didact Lesson09 Monster Maker. Light edit: names Puppet Warp and Smart Object transforms explicitly as the lesson's targets.",
 drive=["Lesson09 Monster Maker (Didact)"],
 bell="Scale a photo down, then back up. What happens to it? How could you avoid that?",
 di_note="\"I Do\": Smart Objects, nondestructive transforms, Puppet Warp, linked vs embedded",
 gp_note="\"We Do\": Monster Maker tutorial",
 target="transform Smart Objects nondestructively, including Puppet Warp, by building the Monster Maker composite",
 org="Tutorial steps with a checkpoint at each body part.",
 conn="Extends 5.3's Smart Objects from filters to transforms.",
 collab="Step-checking partners.",
 evid="Stoplight.",
 summ="Stoplight.",
 binder=[], files=[("your monster .psd", "Project Files")], plus="every part is a Smart Object and Puppet Warp is used at least once", minus="parts were rasterized and scaled",
 iep="Chunked tutorial.", ell="Visual step cards.", gt="Add a second creature that interacts with the first.",
 mats=["Photoshop", "Lesson09 files"], notes="",
 intro="Today you'll build a creature from parts, and learn to transform without losing quality.",
 di="A **Smart Object** remembers its original pixels, so scaling down and back up doesn't lose quality. **Puppet Warp** adds pins so you can bend an arm or a tail. A Smart Object can be **embedded** in the file or **linked** to an outside file.",
 cue="Pin the shoulder, pin the wrist, drag the elbow. The arm bends where I want it.",
 q=("What does a Smart Object protect?", "When would you link instead of embed?", "Plan a pose using Puppet Warp: where would the pins go?"),
 gp=["**Open** the Monster Maker files.", "**Convert** parts to Smart Objects.", "**Puppet Warp** one limb.", "**Turn and Talk:** show your best pin placement."],
 disc="What's the most useful thing about Smart Objects so far?",
 refl="Stoplight on Smart Objects.",
 track=""),

dict(n="7.2", title="Text-ure: Layer Styles & Materials", st="EDIT", ex=["EX33"],
 acp=["3.2.e", "5.4.b", "5.4.c"], comp=[],
 source="Existing: Text-ure. Light edit: adds Photoshop's Materials (3D-style surface presets, ACP 5.4.c) and saving a layer style to Styles.",
 drive=["Text-ure"],
 bell="How could you make text look like it's carved in wood, or made of a photo?",
 di_note="\"I Do\": clipping a photo into type, layer styles (bevel, shadow, stroke), saving a style, Materials",
 gp_note="\"We Do\": textured title from a student photo",
 target="apply, edit, and save layer styles and apply a material by creating a textured title from their own photo",
 org="A layer-style recipe card.",
 conn="6.2's clipping mask, now on type.",
 collab="Partners swap saved styles and apply them.",
 evid="Glow & Grow.",
 summ="Glow & Grow.",
 binder=[], files=[("your text-ure .psd", "Project Files")], plus="type stays live and a style is saved", minus="type rasterized, or no style saved",
 iep="Recipe card with exact settings.", ell="Layer style names with thumbnails.", gt="Build a reusable style set for a client.",
 mats=["Photoshop", "Text-ure materials", "Student photos"], notes="Materials appear in recent Photoshop versions; check that the lab's 26.x build has the Materials panel.",
 intro="Today you'll make type out of your own photos.",
 di="Clip a photo into type to fill the letters. **Layer styles** add bevels, shadows, and strokes, and stay editable. Save a combination to the **Styles** panel. **Materials** apply surface looks like metal or wood.",
 cue="Double-click the layer. Every style is a checkbox I can turn off later.",
 q=("How do you fill type with a photo?", "Why are layer styles nondestructive?", "Design a title style for a photo exhibit."),
 gp=["**Set a title** in a heavy font.", "**Clip** your photo into it.", "**Add two layer styles** and save them.", "**Apply a material** and compare."],
 disc="When does a layer style help, and when does it look dated?",
 refl="Glow and Grow.",
 track=""),

dict(n="7.3", title="Advanced Compositing", st="EX", ex=["EX34"],
 acp=["3.1.b", "3.2.a", "3.3.a"], comp=["K8", "T8", "T13"],
 source="Existing: Didact Lesson09 Advanced Compositing Background. Unchanged.",
 drive=["Lesson09 Background (Didact)"],
 bell="Why do some composites look fake? List two giveaways.",
 di_note="\"I Do\": matching light direction, color, and perspective; clipped adjustment layers; shadows",
 gp_note="\"We Do\": Advanced Compositing tutorial, then swap a subject onto a new background (green-screen style)",
 target="match light, color, and perspective across composite sources using clipped adjustment layers and masks",
 org="A 'believability checklist' (light, color, perspective, shadow, edges).",
 conn="Pulls Unit 4's light vocabulary into compositing.",
 collab="Partners run the believability checklist on each other's work.",
 evid="Emoji meter.",
 summ="Emoji meter.",
 binder=["your believability checklist"], files=[("your composite .psd", "Project Files")], plus="all five checklist items pass", minus="mismatched light or hard cut-out edges",
 iep="Checklist with photo examples.", ell="Visual checklist.", gt="Add a cast shadow and reflection.",
 mats=["Photoshop", "Lesson09 Background files", "Green-screen backdrop (if available)"], notes="TSA semifinal tasks may include green screen; a quick subject swap against the backdrop is good practice.",
 intro="A great composite makes the viewer believe. Today you'll learn the five things that give fakes away.",
 di="Composite sources must match in **light direction**, **color**, **perspective**, and **edge softness**, and the subject needs a **shadow**. Clip an adjustment layer to one source so it changes only that layer.",
 cue="The light in the background comes from the left; my subject is lit from the right. I'll flip her.",
 q=("Name the five believability checks.", "Why clip an adjustment layer?", "How would you light a subject for a background you haven't seen yet?"),
 gp=["**Complete** the tutorial.", "**Swap** a subject onto a new background.", "**Run the checklist** with your partner.", "**Fix** the weakest item."],
 disc="What composite giveaway is hardest to fix?",
 refl="Emoji meter on compositing.",
 track="TSA: save unaltered source images for every composite (required in References)."),

dict(n="7.4", title="Generative AI Tools & the Ethics Line", st="NEW", ex=[],
 acp=["1.2.a", "4.1.b", "4.1.c"], comp=["T15"],
 source="NEW. ACP 4.1.c (generative AI prompts, Generative Fill/Expand, Sky Replacement) and 1.2.a (AI-generated content) have no existing coverage. TSA's honor statement bans generative AI in portfolio images, so this lesson teaches the tools for the exam and draws the line for competition work.",
 drive=[],
 bell="If AI makes part of a photo, is it still your photo?",
 di_note="\"I Do\": Generative Fill and Expand, prompts, Remove Background, Sky Replacement, Content Credentials; TSA and SkillsUSA rules",
 gp_note="\"We Do\": try each tool on a practice image, then a structured debate",
 target="use Generative Fill, Remove Background, and Sky Replacement, and explain when AI-generated content may and may not be used",
 org="A tool card plus a 'where it's allowed' chart (class project, ACP exam, TSA, SkillsUSA, news).",
 conn="Compares 5.2's Content-Aware Fill (uses your pixels) to Generative Fill (makes new pixels).",
 collab="Four-corners debate on the bell-ringer question.",
 evid="3-2-1 plus a one-paragraph position.",
 summ="3-2-1.",
 binder=["your 'where it's allowed' chart"], files=[("your AI practice file", "Project Files")], plus="the paragraph cites a real rule (TSA honor statement or Content Credentials)", minus="no rule cited",
 iep="Paragraph frame: 'I think ___ because ___. The rule says ___.'",
 ell="Bilingual key terms: generative, prompt, credit, honor statement.",
 gt="Compare Adobe's Content Credentials to a news agency's photo policy.",
 mats=["Photoshop with Generative Fill enabled for student accounts (check district Adobe settings)", "TSA honor statement excerpt", "Practice images"],
 notes="Stub: confirm generative features are enabled for student Adobe IDs before teaching; if not, demo from the teacher account. Keep AI-edited files out of TSA candidates entirely.",
 intro="Photoshop can now make pixels from a text prompt. The exam tests it, and competitions ban it. Today you'll learn both sides.",
 di="**Generative Fill** creates new content in a selection from a text **prompt**; **Generative Expand** extends the canvas. **Remove Background** masks the subject in one click. **Sky Replacement** swaps a sky and matches the light. Adobe attaches **Content Credentials** to show AI was used. TSA's honor statement forbids generative AI in portfolio images.",
 cue="Same selection, two tools. Content-Aware Fill used my pixels. Generative Fill invented new ones. That difference is the whole ethics question.",
 q=("What does Generative Fill need from you?", "How is Generative Fill different from Content-Aware Fill?", "Should photo contests allow AI? Defend a position with one rule."),
 gp=["**Try** Generative Fill, Remove Background, and Sky Replacement on a practice image.", "**Fill in** the 'where it's allowed' chart.", "**Four corners:** stand by your answer to the bell ringer and defend it.", "**Write** a one-paragraph position."],
 disc="Where should the line be for AI in photography?",
 refl="3-2-1, then your one-paragraph position.",
 track="TSA: double-check that no candidate image used any generative tool."),

# ---------------- UNIT 8 ----------------
dict(n="8.1", title="Mixer Brush", st="EX", ex=["EX36"],
 acp=["2.5.a", "4.1.a"], comp=[],
 source="Existing: Didact Lesson10 Mixer Basics. Unchanged.",
 drive=["Lesson10 Mixer (Didact)"],
 bell="How is painting in Photoshop different from painting on paper?",
 di_note="\"I Do\": Brush settings, Mixer Brush (wet, load, mix), brush presets and libraries",
 gp_note="\"We Do\": Mixer Brush tutorial",
 target="paint with the Mixer Brush and custom brush settings by completing the Mixer Basics project",
 org="Brush settings reference card.", conn="Moves from editing photos to painting on them.",
 collab="Step-checking partners.", evid="Stoplight.", summ="Stoplight.",
 binder=[], files=[("your Mixer .psd", "Project Files")], plus="custom brush preset saved", minus="default brush only",
 iep="Chunked tutorial.", ell="Brush-setting picture card.", gt="Create and share a custom brush preset.",
 mats=["Photoshop", "Lesson10 files"], notes="",
 intro="Today you'll paint with digital paint that behaves like the real thing.",
 di="The **Brush** tool's size, hardness, and flow shape every stroke. The **Mixer Brush** mixes colors on the canvas like wet paint: **wet** sets how much it picks up, **load** how much paint it carries, **mix** the blend. Save a favorite as a **brush preset**.",
 cue="Wet high, load low, and it smears the photo like a brush through wet paint.",
 q=("What does the Wet setting control?", "Why save a brush preset?", "Which settings would you use to turn a photo into an oil painting?"),
 gp=["**Open** the Mixer files.", "**Follow the tutorial.**", "**Save a preset.**", "**Turn and Talk:** show one stroke you like."],
 disc="When would a photographer paint on a photo?", refl="Stoplight on brushes.", track=""),

dict(n="8.2", title="Painting & Impressionism", st="EDIT", ex=["EX37", "EX38"],
 acp=["2.4.a", "4.1.a", "4.1.b", "5.4.a"], comp=[],
 source="Existing: Didact Lesson10 Painting and Photoshop Impressionism, merged. Light edit: adds the History Brush and Art History Brush and the eraser family (ACP 4.1.b).",
 drive=["Lesson10 Painting (Didact)", "Photoshop Impressionism"],
 bell="Look at a Monet. What did he paint instead of details?",
 di_note="\"I Do\": Impressionism in brief; History Brush and Art History Brush; Eraser, Background Eraser, Magic Eraser; filters",
 gp_note="\"We Do\": turn a student photo into an Impressionist painting",
 target="turn a photo into a painterly image using brushes, the History Brush, and filters",
 org="A three-step plan card: base, strokes, detail.", conn="Uses 8.1's brushes.",
 collab="Gallery walk with sticky-note feedback.", evid="Glow & Grow.", summ="Glow & Grow.",
 binder=[], files=[("your painting .psd", "Project Files")], plus="painterly result with detail restored by History Brush", minus="a single filter only",
 iep="Plan card with settings.", ell="Short Impressionism reading with images.", gt="Paint in the style of a second movement and compare.",
 mats=["Photoshop", "Lesson10 Painting and Impressionism files", "Monet prints or slides"], notes="",
 intro="Today you'll paint like an Impressionist, starting from your own photo.",
 di="Impressionists painted light and color, not detail. The **History Brush** paints back from an earlier state; the **Art History Brush** paints stylized strokes from it. The **Eraser**, **Background Eraser**, and **Magic Eraser** remove pixels (destructively).",
 cue="I blurred everything. Now the History Brush paints the eyes back in, sharp.",
 q=("What does the History Brush paint from?", "Why is the eraser family destructive?", "Which photo of yours would make the best painting, and why?"),
 gp=["**Pick a photo.**", "**Block in** with filters or big brushes.", "**Restore detail** with the History Brush.", "**Gallery walk.**"],
 disc="Is a painted photo still a photograph?", refl="Glow and Grow.", track=""),

dict(n="8.3", title="Light Painting", st="EX", ex=["EX43"],
 acp=["1.4.a"], comp=["K2", "K10", "T6", "T11"],
 source="Existing: Light Painting (2023 outline; no files found in Drive). Kept as a strong TSA student-choice image and long-exposure practice. Lesson materials need to be rebuilt.",
 drive=[],
 bell="How could a photo show something that was never there all at once?",
 di_note="\"I Do\": long exposure, Bulb mode, tripod, manual focus in the dark, light sources",
 gp_note="\"We Do\": darkened-room light painting in teams",
 target="plan and shoot a long-exposure light painting with a recorded settings log",
 org="Team roles card: camera, painter, timer.", conn="Unit 1's shutter speed, pushed to seconds.",
 collab="Teams of three rotate roles.", evid="Emoji meter with one frame.", summ="Emoji meter.",
 binder=["your settings log"], files=[("your light painting", "Photos")], plus="sharp background and a clear, intentional light shape", minus="camera shake or no plan",
 iep="Pre-set camera.", ell="Role cards with pictures.", gt="Combine a flash-frozen subject with light trails.",
 mats=["Tripods", "Flashlights, LED strips, glow sticks", "Darkened room"], notes="Check for photosensitivity concerns before using flashing lights.",
 intro="Light painting draws in the air with a flashlight while the shutter stays open.",
 di="A **long exposure** keeps the shutter open for seconds. Use a **tripod**, ISO 100, f/8, and 10–30 seconds. Focus manually on where the painter will stand.",
 cue="Thirty seconds, starting now. Painter, go.",
 q=("Why is a tripod required?", "What changes if you double the exposure time?", "Plan a light painting that tells a story."),
 gp=["**Set** the camera on a tripod.", "**Focus** manually.", "**Shoot** three attempts.", "**Log** your settings."],
 disc="What made your best frame work?", refl="Emoji meter.", track="TSA: a strong student-choice candidate."),

dict(n="8.4", title="Vector Shapes, the Pen Tool, Frames & Vector Masks", st="NEW", ex=[],
 acp=["3.2.c", "3.2.d", "4.2.a"], comp=[],
 source="NEW. ACP 4.2.a (Pen and shape tools), 3.2.c (Frame tool), and 3.2.d (vector masks) have no existing coverage in the PDD course. Comes right before S8's Google Doodle, which uses all three.",
 drive=[],
 bell="Why might a logo be drawn with vectors instead of pixels, even in Photoshop?",
 di_note="\"I Do\": shape tools and live shape properties, the Pen tool (anchor points, curves), paths, vector masks, the Frame tool",
 gp_note="\"We Do\": trace a simple shape with the Pen tool, convert it to a vector mask, place a photo in a frame",
 target="draw with the Pen and shape tools and mask with frames and vector masks",
 org="Pen tool practice sheet (straight, curve, corner).", conn="Prepares S8's Doodle.",
 collab="Partners race the Pen practice sheet.", evid="3-2-1 with a screenshot.", summ="3-2-1.",
 binder=["your Pen practice sheet"], files=[("your vector .psd", "Project Files")], plus="clean curves with few anchor points", minus="no vector mask",
 iep="Practice sheet with dots for anchors.", ell="Anchor/handle diagram.", gt="Draw a complex logo with the Pen tool.",
 mats=["Photoshop", "Pen practice sheet (to build)"], notes="Stub: the Pen practice file still needs to be built; FDD's Unit 4 Pen tool materials can be adapted.",
 intro="Photoshop has vectors too. Today you'll draw shapes that never pixelate.",
 di="**Shape tools** make editable vector shapes. The **Pen tool** draws paths with **anchor points**: click for corners, drag for curves. A path can become a **vector mask**. The **Frame tool** makes a placeholder that crops any image placed inside it.",
 cue="Click, click, drag. Two anchors and a handle make this curve.",
 q=("Click or drag: which makes a curve?", "Why would you use a vector mask instead of a pixel mask?", "Plan the fewest anchor points for a heart shape."),
 gp=["**Complete** the Pen practice sheet.", "**Make** a vector mask from a path.", "**Place** a photo into a frame.", "**Partner check.**"],
 disc="When is vector better than pixels in Photoshop?", refl="3-2-1 on vectors.", track=""),

# ---------------- UNIT 9 ----------------
dict(n="9.1", title="Client Communication & Project Management", st="NEW", ex=[],
 acp=["1.1.b", "1.1.c", "1.1.d"], comp=["K12", "T14"],
 source="NEW. ACP 1.1.c (communicating design plans) and 1.1.d (project management: scope, scope creep, timelines, file management) have only a light touch in 3.1. Also prepares the TSA interview and SkillsUSA job interview.",
 drive=[],
 bell="A client keeps asking for 'just one more change.' What's the problem?",
 di_note="\"I Do\": design briefs, mood boards, sketches, specs, style guides; scope and scope creep; timelines; file naming and versioning",
 gp_note="\"We Do\": read a brief, write a project plan, role-play a client meeting",
 target="read a brief and write a project plan with scope, timeline, and file plan, and present it in a mock client meeting",
 org="Project plan template.", conn="Starts S9: the portfolio is the project.",
 collab="Client/designer role-play in pairs.", evid="Stoplight plus the plan.", summ="Stoplight.",
 binder=["your project plan"], files=[], plus="the plan names scope limits and a dated timeline", minus="no timeline",
 iep="Template with examples.", ell="Meeting sentence frames.", gt="Write a change-order policy.",
 mats=["Sample brief", "Project plan template"], notes="Stub: write the sample brief (a photo client).",
 intro="Real photographers work for clients. Today you'll plan a project the way they do.",
 di="A **brief** says what the client needs. You answer with **sketches**, **mood boards**, and **specs**. **Scope** is what's included; **scope creep** is extras that sneak in. A **timeline** sets deadlines. A file plan keeps versions straight.",
 cue="'That's a great idea. It's outside our scope, so here's what it would add to the timeline.'",
 q=("What is scope creep?", "Why write a timeline before starting?", "How would you handle a client who wants a different style halfway through?"),
 gp=["**Read** the sample brief.", "**Write** a project plan.", "**Role-play** a client meeting.", "**Swap roles.**"],
 disc="What makes a client meeting go well?", refl="Stoplight.", track="Mock interview questions for SkillsUSA and TSA."),

dict(n="9.2", title="Web-Ready Portfolio & Accessibility", st="EDIT", ex=["EX42", "EX45"],
 acp=["1.1.a", "6.1.b", "6.2.b"], comp=[],
 source="Existing: Web Safe Design deck and the cumulative Google Sites portfolio. Light edit: adds accessibility (alt text, contrast, ACP 1.1.a) and export settings for web.",
 drive=["Web Safe Design (slides)"],
 bell="A photo loads slowly on your phone. What might be wrong with the file?",
 di_note="\"I Do\": web file formats, file size, sRGB, alt text and contrast",
 gp_note="\"We Do\": export three images for web and add them with alt text to the Google Sites portfolio",
 target="export images for the web and add them to a portfolio page with alt text and readable contrast",
 org="Web export checklist.", conn="Feeds S9's web portfolio.",
 collab="Partners test each other's page on a phone.", evid="Glow & Grow.", summ="Glow & Grow.",
 binder=[], files=[("your web exports", "Exports")], plus="files under 500 KB with descriptive alt text", minus="huge files or no alt text",
 iep="Checklist with screenshots.", ell="Alt-text sentence frame.", gt="Compare JPEG quality settings and report file sizes.",
 mats=["Photoshop", "Google Sites"], notes="",
 intro="Your portfolio has to load fast and work for everyone.",
 di="Web images use **JPEG** (photos) or **PNG** (transparency) in **sRGB**. Keep files small. **Alt text** describes an image for screen readers. Text needs strong **contrast** against its background.",
 cue="Alt text isn't 'photo.' It's 'Senior Maya Ortiz leaps for a header at the homecoming game.'",
 q=("Which format for a photo on the web?", "Why does alt text matter?", "Write alt text for your best photo."),
 gp=["**Export** three images.", "**Add** them to your site.", "**Write** alt text.", "**Phone test.**"],
 disc="Who is helped by alt text?", refl="Glow and Grow.", track=""),

dict(n="9.3", title="Save, Export & Nondestructive Workflow", st="NEW", ex=[],
 acp=["1.3.c", "2.2.b", "2.3.a", "6.1.a", "6.1.b", "6.2.a", "6.2.b"], comp=["T9"],
 source="NEW. ACP Domain 6 (Export Layers/Artboards, Quick Export, Export As, save formats, color space, bit depth) and linked Smart Objects/packaging (2.3.a) aren't taught directly anywhere in the existing course.",
 drive=[],
 bell="You send a client a file and they can't open it. List three things that might have gone wrong.",
 di_note="\"I Do\": PSD vs TIFF vs JPEG vs PNG; bit depth and color space; Quick Export, Export As, Export Layers/Artboards; linked files and Package; cloud documents",
 gp_note="\"We Do\": export one project five ways; package a file with linked Smart Objects",
 target="save and export files in the right format, color space, and bit depth for a given use",
 org="Export decision chart.", conn="Pulls together every unit's saving habits.",
 collab="Partners test each other's exports.", evid="Fix-This-File: a misexported file to correct.", summ="Emoji meter.",
 binder=["your export chart"], files=[("your exports", "Exports")], plus="all five exports match their use", minus="wrong format or color space",
 iep="Chart with examples.", ell="Format icons with uses.", gt="Write an export spec for a client.",
 mats=["Photoshop", "A project with linked Smart Objects"], notes="Stub: build the Fix-This-File start file (CMYK image meant for web, 16-bit JPEG attempt, missing linked file).",
 intro="A file is only done when it's delivered right.",
 di="Save working files as **PSD**. Export **JPEG** for photos on screens, **PNG** for transparency, **TIFF** for print. Use **sRGB** for screens and the printer's profile for print. **Quick Export** is fast; **Export As** gives control. **Export Layers/Artboards** makes many files at once. **Package** gathers linked files.",
 cue="Same image, five uses, five exports. The format follows the job.",
 q=("Which format keeps transparency?", "Why do colors look dull when a CMYK file goes to the web?", "Write the export settings for a 16×20 print and an Instagram post."),
 gp=["**Export** one project five ways.", "**Package** a file.", "**Fix** the broken file.", "**Partner test.**"],
 disc="What's the most common delivery mistake?", refl="Emoji meter.", track="TSA: export your portfolio images at print size."),

dict(n="9.4", title="Print Presentation: Mounting, Matting & the Portfolio PDF", st="NEW", ex=[],
 acp=["6.2.b"], comp=["K11", "T9"],
 source="NEW. SkillsUSA requires 11×14 prints mounted on 16×20 foam core with a 16×20 black mat and an 11×14 window; TSA requires a specifically ordered PDF portfolio. Neither is taught in the existing course.",
 drive=[],
 bell="A print looks great on screen but dark on paper. Why?",
 di_note="\"I Do\": print sizing (11×14 at 300 ppi = 3300 × 4200 px), soft proofing, mounting and matting; TSA PDF order",
 gp_note="\"We Do\": mat-window math, assemble the portfolio PDF skeleton",
 target="prepare a print to competition specifications and assemble a portfolio PDF in TSA's required order",
 org="Spec sheet for both competitions.", conn="Final step before S9.",
 collab="Partners check each other's PDF order.", evid="3-2-1 with the mat math.", summ="3-2-1.",
 binder=["your spec sheet"], files=[("your portfolio PDF draft", "Exports")], plus="correct math and PDF order", minus="math errors or missing sections",
 iep="Worked math example.", ell="Spec sheet diagrams.", gt="Calculate a custom mat for a different print ratio.",
 mats=["Foam core, mat board, mat cutter (competition track)", "Spec sheet"], notes="Stub: build the spec sheet. Prints at 11×14 cost money; competition-track only.",
 intro="Today you'll prepare work the way judges will see it.",
 di="An **11×14** print at 300 ppi needs **3300 × 4200 px**. A 16×20 mat with an 11×14 window leaves borders of 2.5 in (left/right) and 3 in (top/bottom). TSA's PDF order: title page, table of contents, theme summary, five images, statements, references, forms.",
 cue="16 minus 11 is 5, split two ways: 2.5 inches each side.",
 q=("How many pixels for an 11×14 at 300 ppi?", "Why soft-proof before printing?", "Design a mat for an 8×10 print."),
 gp=["**Solve** the mat math.", "**Build** the PDF skeleton.", "**Soft-proof** one image.", "**Partner check.**"],
 disc="What makes a print presentation professional?", refl="3-2-1.", track="Mount two prints for SkillsUSA."),
]
