# PDD revision lessons, Units 3-5.
LESSONS_B = [
# ---------------- UNIT 3 ----------------
dict(n="3.1", title="Planning the Shoot, Framing & the News Photo", st="EDIT", ex=["EX06", "EX07", "EX14"],
 acp=["1.1.a", "1.1.d", "1.4.a"], comp=["K4", "T1", "T12"],
 source="Existing: Planning your Shoot, Framing, and What Makes a Good News Photo, merged into one lesson (each was about a single period of slides). Light edit: the shot list now carries a simple timeline and file-naming plan, which introduces ACP 1.1.d project management; Unit 9 finishes it.",
 drive=["Planning your Shoot (slides)", "What Makes a Good News Photo (slides)"],
 di_note="\"I Do\": purpose and audience, the shot list (wide, medium, close, detail, reaction), framing, the qualities of a news photo",
 gp_note="\"We Do\": analyze three news photos, then write a shot list for the S3 event",
 target="plan a photo assignment around its purpose and audience by writing a shot list, timeline, and file-naming plan for an upcoming school event",
 org="A shot-list template with columns for shot type, subject, and time.",
 conn="Reuses 1.4's composition and framing, now aimed at telling a true story.",
 collab="Think-Pair-Share analysis of three news photos; partners trade shot lists for a 'what's missing' check.",
 evid="A completed shot list with at least eight shots, a timeline, and a naming plan.",
 summ="Stoplight on readiness to shoot the event.",
 binder=["your shot list"], files=[], plus="the list covers every shot type and names a specific moment for each", minus="fewer than five shots, or no timeline",
 iep="Partially filled shot list with the five shot types already in the first column.",
 ell="Shot-type picture cards (wide, medium, close, detail, reaction).",
 gt="Add a 'story arc' column: which shot opens the story, which ends it.",
 mats=["Three printed news photos (local paper or AP)", "Shot-list template", "School events calendar"],
 notes="Pick the S3 event now; sports, a club meeting, or a pep rally work. Release forms (3.3) should go home before the shoot.",
 intro="News photographers don't wander around hoping. They plan. Today you'll plan the event you'll cover for S3.",
 di="Every assignment starts with **purpose** (what's the story?) and **audience** (who will see it?). A **shot list** makes sure you come back with a full story: a **wide** establishing shot, **medium** action, a **close-up**, a **detail**, and a **reaction**. **Framing** within the scene isolates the subject. A strong news photo shows emotion, action, and a decisive moment.",
 cue="If my editor can only run one of these, it's the one with a face reacting. Emotion beats everything.",
 q=("Name the five shot types on a shot list.", "Why does a reaction shot often tell more of the story than the action?", "Write the one photo you'd need to tell this event's story if you could only take one."),
 gp=["**Think-Pair-Share:** for each of three news photos, name the story, the shot type, and the framing.",
     "**Choose your event** and write its purpose and audience in one sentence each.",
     "**Write a shot list** of at least eight shots, with when each is likely to happen.",
     "**Trade lists** with a partner. They mark one shot that's missing."],
 disc="What makes a photo 'news' instead of just a nice picture?",
 refl="Are you ready to shoot your event? Rate yourself and name one thing you still need.",
 track="SkillsUSA K4 practice: given a surprise theme, write a 6-shot list in 5 minutes."),

dict(n="3.2", title="Cropping, Resolution & Image Size", st="EDIT", ex=["EX12", "EX41"],
 acp=["1.3.a", "2.1.a", "5.3.a", "6.2.b"], comp=["K9", "K10"],
 source="Existing: Photo Cropping deck and Resolution & Image Size deck, merged. Light edit: adds the Crop tool's aspect-ratio presets, Straighten, and the Resample checkbox in Image Size, which ACP 5.3.a names.",
 drive=["Photo Cropping (slides)", "Resolution & Image Size (slides)"],
 di_note="\"I Do\": cropping for impact, Crop tool ratios and Straighten, ppi vs pixel dimensions, Image Size with and without resampling",
 gp_note="\"We Do\": crop one photo three ways, then resize it for print and for Instagram",
 target="crop a photo for impact and set its resolution and image size for print and screen by producing three crops and two correctly sized exports",
 org="A resolution cheat sheet (ppi × inches = pixels) sits next to each Mac.",
 conn="Picks up 2.2's resolution setting and 1.4's aspect ratio.",
 collab="Turn and Talk: partners vote on which crop is strongest before the teacher reveals the editor's choice.",
 evid="Two-Minute Drill: resize an image to exactly 1080 px wide without changing its proportions, screenshot the Image Size dialog.",
 summ="Glow & Grow.",
 binder=["your resolution cheat sheet"], files=[("your three crops", "Photos")], plus="each crop has a clear reason and the Image Size math is correct", minus="the resized file is distorted or the resolution is wrong",
 iep="Cheat sheet with worked examples; calculator allowed.",
 ell="Sentence frame: 'This image is ___ px wide, so at ___ ppi it prints ___ inches wide.'",
 gt="Find the largest print size this photo can make at 300 ppi without resampling, and the smallest acceptable ppi for a billboard seen from 100 ft.",
 mats=["Photoshop", "Sample photos from the S3 shoot or a provided set", "Resolution cheat sheet"],
 notes="Every exit ticket this unit can include a 'why does this look wrong?' image (pixelated, stretched) for SkillsUSA K10.",
 intro="A crop can make or break a photo, and a resize done wrong ruins it. Today you'll do both right.",
 di="**Crop** to remove distractions and strengthen composition. The Crop tool can lock an **aspect ratio** (4:5, 16:9) and **Straighten** a tilted horizon. **Resolution** (ppi) only matters for print: pixels ÷ ppi = inches. In **Image → Image Size**, unchecking **Resample** changes ppi without changing pixels; checking it adds or throws away pixels.",
 cue="Watch the pixel count. If I uncheck Resample, it doesn't move. I'm not changing the photo, just how big it prints.",
 q=("What does ppi stand for?", "Why does making an image bigger with Resample on often look soft?", "A client needs this photo for a 24 × 36 in poster. Can it work? Show the math."),
 gp=["**Crop three ways:** tight, rule-of-thirds, and a 4:5 social crop. Save each.",
     "**Straighten** one tilted photo with the Crop tool's Straighten option.",
     "**Resize for print:** 8 × 10 in at 300 ppi. Note the pixel dimensions.",
     "**Resize for screen:** 1080 px wide. Turn and Talk: which resize lost information?"],
 disc="When is it okay to crop a news photo, and when would cropping change the truth?",
 refl="Glow and Grow: which crop worked best and what would you do differently?",
 track="SkillsUSA troubleshooting card: identify the cause of a pixelated print, a stretched face, and a tilted horizon."),

dict(n="3.3", title="Photo Usage Rights & Releases", st="EDIT", ex=["EX13"],
 acp=["1.2.a", "1.2.b"], comp=["T8", "T10"],
 source="Existing: Photo Usage Rights deck and Sharpening Photo Search Skills. Light edit: adds model and location releases (ACP 1.2.b, missing from the existing deck) and introduces the TSA Student Copyright Checklist and release forms that every TSA portfolio needs.",
 drive=["Photo Usage Rights (slides)", "Sharpening Photo Search Skills"],
 di_note="\"I Do\": copyright, fair use, Creative Commons licenses, public domain, AI-generated content, model and location releases",
 gp_note="\"We Do\": license scenarios, then fill out a model release for a classmate",
 target="decide whether an image can legally and ethically be used, and when a release is needed, by sorting eight scenarios and completing a model release",
 org="A decision flowchart: who made it, what license, what use, is a person recognizable?",
 conn="Students are about to photograph real people at the S3 event; releases make that publishable.",
 collab="Scenario cards sorted in pairs, then cold-call to defend one sort.",
 evid="Completed scenario sort plus one signed practice model release.",
 summ="Emoji meter on copyright.",
 binder=["your scenario sort", "your practice release"], files=[], plus="every scenario sorted correctly with the license or rule named", minus="more than two scenarios wrong",
 iep="Flowchart with yes/no arrows; four scenarios instead of eight.",
 ell="Key-term cards: copyright, license, attribution, release, public domain.",
 gt="Write the Creative Commons attribution line for two images correctly, and explain how fair use's four factors apply to one scenario.",
 mats=["Scenario cards", "Model release and location release forms (district or TSA versions)", "TSA Student Copyright Checklist"],
 notes="Minors need a parent/guardian signature on releases for TSA. Send the releases home now so they're back before the S3 shoot.",
 intro="Just because you can find an image doesn't mean you can use it. And photographing people comes with responsibilities.",
 di="**Copyright** belongs to whoever made the image, automatically. You can use someone else's work if it's **public domain**, if the **license** allows it (Creative Commons licenses say how: attribution, no commercial use, no changes), or under limited **fair use**. AI-generated images raise their own rules. If a person is recognizable in a photo used to promote something, you need a **model release**; private property may need a **location release**.",
 cue="I'll read this license out loud. CC BY-NC: I must credit the photographer, and I can't use it to sell anything.",
 q=("Who owns the copyright to a photo you take?", "Why does a recognizable face in an advertisement need a release when a news photo usually doesn't?", "You want to use a classmate's photo in your TSA portfolio. What do you need, and from whom?"),
 gp=["**Sort the scenarios** with your partner: can use / can use with conditions / can't use.",
     "**Cold call:** defend one sort with the license or rule.",
     "**Fill out a model release** for your partner as practice.",
     "**Read** the TSA Student Copyright Checklist and highlight the parts that apply to photos."],
 disc="Is it fair to use a photo you found online if you give credit? Why or why not?",
 refl="How confident are you about when you can use an image? Name one rule you'll remember.",
 track="TSA: start the portfolio's References page and collect releases for anyone in your candidate images."),

dict(n="3.4", title="Captions & Cutlines", st="EDIT", ex=["EX10"],
 acp=["1.1.a"], comp=["T7", "K4"],
 source="Existing: Craft the Cutline. Light edit: adds a second format, the TSA image statement (camera, f-stop, exposure time, ISO, focal length, description, theme, edits), written from the same photo so students see the two forms side by side.",
 drive=["Craft the Cutline"],
 di_note="\"I Do\": the 5 Ws cutline formula, present tense, names and IDs; the TSA image statement format",
 gp_note="\"We Do\": rewrite three weak cutlines, then write a cutline and a TSA statement for one of your own photos",
 target="write an accurate cutline that answers the 5 Ws, and a TSA-format image statement, for one of their own photos",
 org="A cutline template (who, what, when, where, why) next to a statement template.",
 conn="Uses the settings log from Unit 1: the statement's metadata comes straight from it.",
 collab="Partners fact-check each other's cutlines: is every name and detail verifiable?",
 evid="One cutline and one statement for the student's own photo.",
 summ="3-2-1.",
 binder=["your cutline and statement draft"], files=[], plus="the cutline answers all 5 Ws and the statement lists all five settings", minus="names missing or settings incomplete",
 iep="Cutline frame with blanks for each W.",
 ell="Sentence frame: '[Name], [grade], [action] during [event] on [date] at [place].'",
 gt="Write a 150-word photo story to accompany the image.",
 mats=["Craft the Cutline materials", "Statement template", "Students' Unit 1 or S3 photos"],
 notes="Image statements are a TSA requirement: half a page per image in 12-pt Times New Roman, kept off the image page.",
 intro="A photo without a caption leaves readers guessing. Today you'll write captions that tell the whole story.",
 di="A **cutline** answers **who, what, when, where, why** in present tense, with full names and identifiers. A **TSA image statement** is longer: camera make and model, **f-stop**, **exposure time**, **ISO**, **focal length**, a description, how it fits the theme, and the edits you made.",
 cue="'Senior Maya Ortiz celebrates…' Present tense, full name, grade. The reader knows exactly who and what.",
 q=("What are the 5 Ws?", "Why are cutlines written in present tense?", "How could the same photo need a different cutline for the yearbook and for a contest statement?"),
 gp=["**Fix three weak cutlines** from the deck with your partner.",
     "**Pick one of your photos** and write its cutline.",
     "**Write its TSA statement** using your settings log for the metadata.",
     "**Fact-check swap:** your partner circles anything they can't verify."],
 disc="Why do you think TSA wants the camera settings in the statement?",
 refl="Write 3 things you wrote, 2 rules you used, and 1 question.",
 track="TSA: save this statement as the first draft in your portfolio statements doc."),

# ---------------- UNIT 4 ----------------
dict(n="4.1", title="Quality of Light", st="EDIT", ex=["EX17"],
 acp=["1.4.a"], comp=["K1", "T11"],
 source="Existing: Lighting deck. Light edit: adds white balance and color temperature (named in ACP 1.4.a and on the SkillsUSA written test).",
 drive=["Lighting (slides)"],
 di_note="\"I Do\": hard vs soft light, direction (front, side, back), color temperature in Kelvin, white balance presets",
 gp_note="\"We Do\": photograph one subject in three light directions and three white-balance settings",
 target="describe light by quality, direction, and color, and set white balance to match, by shooting a labeled light-direction set and a white-balance set",
 org="A light-description chart (quality / direction / color) to fill in for each frame.",
 conn="Unit 1 controlled how much light; now students control what kind.",
 collab="Partners hold the reflector and the subject while the other shoots; switch halfway.",
 evid="Six labeled frames (three directions, three white balances).",
 summ="Stoplight.",
 binder=["your light-description chart"], files=[], plus="every frame is labeled with quality, direction, and Kelvin or preset", minus="fewer than four frames, or labels missing",
 iep="Chart with check-boxes instead of written labels.",
 ell="Picture cards for hard, soft, front, side, back light.",
 gt="Shoot a seventh frame with mixed light sources and correct it with a custom white balance.",
 mats=["DSLRs", "Desk lamp or window light", "Reflector or white foam board", "Lighting deck"],
 notes="Lighting vocabulary is heavily weighted on the SkillsUSA written test (Quality of Light).",
 intro="Photography means 'drawing with light.' Today you'll learn to describe it, and then to choose it.",
 di="Light has a **quality**: **hard** light (small source, sharp shadows) or **soft** light (large or diffused source, gentle shadows). It has a **direction**: front, side, or back. It has a **color**, measured in **Kelvin**: candlelight about 1900 K, daylight about 5500 K, shade about 7000 K. **White balance** tells the camera what color 'white' should be.",
 cue="I'm going to move this lamp from the front to the side. Watch what happens to the texture on the face.",
 q=("Which makes softer light: a bare bulb or a window with a curtain?", "Why does side light show texture better than front light?", "You're shooting under orange gym lights. What white balance do you choose, and what happens if you leave it on Auto?"),
 gp=["**Direction set:** photograph your partner lit from the front, side, and back.",
     "**White balance set:** shoot the same frame on Daylight, Tungsten, and Auto.",
     "**Fill in the chart** for all six frames.",
     "**Turn and Talk:** which direction flattered your subject most?"],
 disc="What mood does side light create compared to front light?",
 refl="Stoplight: how ready are you to describe light in a photo? Explain.",
 track="Flashcards: hard light, soft light, Kelvin, white balance, catchlight."),

dict(n="4.2", title="Shaping Light: Studio Patterns & Off-Camera Flash", st="EDIT", ex=["EX18"],
 acp=["1.4.a"], comp=["K6", "K7", "T13"],
 source="Existing: Shaping Light deck. Light edit: adds the off-camera flash setup (Godox X Pro-C trigger, X1R-C receiver, Canon 600EX-RT in M) and a light-meter exercise for main/fill ratios, both judged in competition (SkillsUSA studio portrait and meter; TSA semifinal off-camera flash).",
 drive=["Shaping Light (slides)"],
 di_note="\"I Do\": the five portrait patterns (split, loop, Rembrandt, butterfly, broad/short), main and fill, the flash trigger setup, reading a meter",
 gp_note="\"We Do\": rotating stations: each team lights one pattern with the off-camera flash and meters main and fill",
 target="set up and name the basic portrait lighting patterns with an off-camera flash, and measure a main/fill ratio, by shooting three labeled patterns at stations",
 org="Station cards show each pattern's diagram (light angle and height) and a sample photo.",
 conn="4.1 described light; today students place it on purpose.",
 collab="Teams of three rotate roles: subject, light, camera.",
 evid="Three labeled pattern frames, plus one recorded main/fill ratio.",
 summ="Glow & Grow.",
 binder=["your pattern diagram sheet"], files=[], plus="all three patterns are identifiable and the ratio is recorded in stops", minus="patterns mislabeled or no meter reading",
 iep="Station cards with taped floor marks for the light stand position.",
 ell="Pattern names paired with diagrams; a sentence frame for the ratio.",
 gt="Recreate a classic film portrait's lighting and diagram it.",
 mats=["Canon 600EX-RT Speedlites, Godox X Pro-C transmitters, X1R-C receivers, light stands, umbrellas", "Handheld light meter (if available) or the camera's histogram", "Teacher Tools: Godox flash trigger guide"],
 notes="Use the site's Godox flash trigger guide for setup. Clear the Speedlite settings first, set it to M, and use NiMH rechargeables.",
 intro="Studio photographers don't hope for good light; they build it. Today you'll build five classic portrait looks.",
 di="Portrait lighting patterns are named for the shadow they make. **Split**: half the face lit. **Loop**: a small nose shadow loops toward the cheek. **Rembrandt**: a triangle of light on the shadow-side cheek. **Butterfly**: a shadow under the nose from light high in front. **Broad/short**: lighting the side of the face toward or away from the camera. The **main** light makes the pattern; a **fill** softens the shadows. The **lighting ratio** compares them in stops.",
 cue="Main reads f/8, fill reads f/5.6. That's one stop apart, a 2:1 ratio. Gentle shadows.",
 q=("Which pattern makes a triangle of light on the cheek?", "Why would a photographer choose split light for a dramatic sports portrait?", "Your subject has glasses and the flash reflects. What would you change, and why?"),
 gp=["**Set up** the trigger and flash with the guide (clear settings, M mode, channel and group).",
     "**Station rotation:** light and shoot split, loop, and Rembrandt.",
     "**Meter** the main and fill at one station and record the ratio.",
     "**Turn and Talk:** which pattern suits which kind of portrait?"],
 disc="How does moving the main light change the subject's mood?",
 refl="Glow and Grow from today's studio work.",
 track="SkillsUSA: complete all five patterns and a 3:1 ratio with the meter."),

dict(n="4.3", title="Black & White, Tonal Range & the Histogram", st="EDIT", ex=["EX20"],
 acp=["1.3.b", "3.3.a", "3.3.b"], comp=["T3", "T11"],
 source="Existing: Ansel Adams deck. Light edit: adds the Photoshop side: a Black & White adjustment layer, Levels/Curves read against the histogram, color modes and bit depth, and saving an adjustment preset, all named in ACP 1.3.b and 3.3.",
 drive=["Ansel Adams (slides)"],
 di_note="\"I Do\": Ansel Adams and the Zone System; the histogram; color modes and bit depth; Black & White and Levels adjustment layers; adjustment presets",
 gp_note="\"We Do\": convert one of your photos to B&W with an adjustment layer and correct its tones with Levels",
 target="convert an image to black and white with an adjustment layer, read and correct its histogram, and save an adjustment preset",
 org="A histogram reading card: left = shadows, right = highlights, gaps = missing tones.",
 conn="4.1's light becomes tone: in B&W, light and shadow are all you have.",
 collab="Partners read each other's histograms out loud before editing.",
 evid="Screenshot Receipt: Layers panel with the B&W and Levels adjustment layers, and the Histogram panel.",
 summ="Emoji meter.",
 binder=["your histogram card"], files=[("your B&W .psd", "Project Files")], plus="tones run from true black to true white without clipping, and a preset is saved", minus="the conversion used Image → Mode → Grayscale (destructive) or has no adjustment layer",
 iep="Pre-chosen photo and a step card for the two adjustment layers.",
 ell="Histogram card with arrows labeled shadows / midtones / highlights.",
 gt="Use the B&W adjustment's color sliders to darken a sky like Adams did with a red filter, and explain why that works.",
 mats=["Photoshop", "Ansel Adams deck", "Students' own photos"],
 notes="Good B&W candidates feed TSA's required B&W image.",
 intro="Ansel Adams made some of the most famous photographs ever, without any color. Today you'll learn how tone does the work.",
 di="A **histogram** graphs how many pixels sit at each brightness, from black on the left to white on the right. A photo that touches both ends has full **tonal range**. **Color mode** (RGB, CMYK, Grayscale) and **bit depth** (8 or 16 bits per channel) set how many tones are possible. Convert to B&W with a **Black & White adjustment layer**, not by changing the mode, so it stays editable, then fix tones with **Levels**. Save settings you like as an **adjustment preset**.",
 cue="This histogram is bunched in the middle: no true blacks, no true whites. That's why it looks flat. Watch me drag the Levels sliders in to the edges.",
 q=("What does the left side of a histogram show?", "Why use an adjustment layer instead of Image → Mode → Grayscale?", "How would you use the B&W color sliders to make a red jersey pop against green grass?"),
 gp=["**Open** a photo with a range of colors.",
     "**Add a Black & White adjustment layer** and move the color sliders.",
     "**Add Levels** and stretch the tones to the histogram's edges.",
     "**Save a preset** from the adjustment's menu; Turn and Talk about your settings."],
 disc="When does a photo work better in black and white than in color?",
 refl="How confident are you reading a histogram? Explain with today's photo.",
 track="TSA: pick your B&W candidate and log the edits for its statement."),

dict(n="4.4", title="Still Life & Macro", st="NEW", ex=[],
 acp=["1.4.a"], comp=["T4", "T5", "T13"],
 source="NEW. TSA requires a macro image and a still-life image in every portfolio, and the semifinal shoot can include product shots; nothing in the existing course teaches either.",
 drive=[],
 di_note="\"I Do\": still life arrangement (odd numbers, triangles, negative space), product lighting, macro: minimum focus distance, magnification, depth of field at close range, tripod use",
 gp_note="\"We Do\": tabletop stations: one still-life arrangement and one macro subject per team",
 target="light and shoot a still life and a macro subject by producing one of each with a tripod and a recorded setting log",
 org="Two station cards: still life (arrangement checklist) and macro (focus and depth checklist).",
 conn="Uses 4.1's soft light and 4.2's off-camera flash on objects instead of people.",
 collab="Teams arrange and critique the still life together before shooting.",
 evid="One still life and one macro frame with settings logged.",
 summ="3-2-1.",
 binder=["your settings log"], files=[("your still life and macro frames", "Photos")], plus="both frames are tack-sharp where intended and the arrangement shows a clear design choice", minus="either frame is out of focus or missing",
 iep="Pre-arranged still-life set; macro station with focus point marked.",
 ell="Station cards with photos of finished examples.",
 gt="Shoot a product shot on a seamless background with a single off-camera flash and a reflector.",
 mats=["Tripods", "Tabletop sweep (poster board)", "Clip-on macro lenses or extension tubes if available; otherwise the kit lens at 55 mm and closest focus", "Small objects: fruit, leaves, coins, jewelry"],
 notes="Stub: the station cards and a short example slide set still need to be built. If no macro lens is available, 'close-up' with the kit lens plus cropping is enough for a first pass; extension tubes are an inexpensive add.",
 intro="TSA portfolios need a still life and a macro photo. Today you'll shoot both.",
 di="A **still life** is an arrangement of objects, lit and composed on purpose. Odd numbers, varied heights, and a triangle shape help. **Macro** photography shows a small subject life-size or larger. Up close, **depth of field** gets very shallow, so use a **tripod**, a smaller aperture, and focus carefully.",
 cue="At this distance, f/5.6 gives me a sliver of focus. I'll go to f/11 and lock the camera down.",
 q=("What is macro photography?", "Why does depth of field get shallower as you move closer?", "Design a still life that tells a story about a person without showing them."),
 gp=["**Still life:** arrange three to five objects, light them with soft side light, and shoot on a tripod.",
     "**Critique:** Turn and Talk with your team: what one change would improve the arrangement?",
     "**Macro:** fill the frame with a small texture. Try f/5.6 and f/11.",
     "**Log** both frames' settings."],
 disc="What's the difference between a still life and a product shot?",
 refl="Write 3 things you shot, 2 techniques, and 1 question.",
 track="TSA: choose your still-life and macro candidates."),

# ---------------- UNIT 5 ----------------
dict(n="5.1", title="Red Eye, Brighten, Liquify & Dodge/Burn", st="EDIT", ex=["EX21"],
 acp=["3.3.a", "5.2.a", "5.2.b", "5.3.b"], comp=["K9", "K10"],
 source="Existing: Didact Lesson05 RedEye/Brighten/Liquify. Light edit: adds Dodge, Burn, and Sponge (ACP 5.2.b) and an 'avoid over-manipulation' check, which SkillsUSA judges.",
 drive=["Lesson05 RedEye/Brighten/Liquify (Didact)"],
 di_note="\"I Do\": Red Eye tool, brightening with an adjustment layer, Liquify, Dodge/Burn/Sponge on a duplicate layer",
 gp_note="\"We Do\": retouch the tutorial portrait, then one of your own",
 target="retouch a portrait with Red Eye, adjustment layers, Liquify, and Dodge/Burn/Sponge without over-editing",
 org="A retouching checklist with an 'is it still believable?' check at the end.",
 conn="Uses 4.3's adjustment layers; applies them to people.",
 collab="Partners do a before/after blink test: is the edit noticeable?",
 evid="Stoplight exit ticket with a planted-error image to diagnose.",
 summ="Stoplight.",
 binder=["your retouching checklist"], files=[("your retouched portrait", "Project Files")], plus="edits are believable and done on separate layers", minus="edits are destructive or obviously overdone",
 iep="Tutorial chunked into four checkpoints.",
 ell="Before/after picture cards for each tool.",
 gt="Write a short ethics note: where does retouching become misleading in news photos?",
 mats=["Photoshop", "Lesson05 files", "Students' Unit 4 portraits"],
 notes="Planted error for today's exit ticket: a portrait with a blown-out highlight.",
 intro="Retouching is about making a photo better, not fake. Today you'll learn the classic tools and the line not to cross.",
 di="**Red Eye** fixes flash reflection in pupils. **Brighten** with a Curves or Levels adjustment layer. **Liquify** pushes pixels (use sparingly). **Dodge** lightens, **Burn** darkens, and **Sponge** changes saturation; work on a duplicate layer so the original stays safe.",
 cue="I'll dodge just the eyes, 10% exposure. If you notice it, I went too far.",
 q=("What does the Burn tool do?", "Why work on a duplicate layer?", "Where's the line between retouching and misrepresenting a person?"),
 gp=["**Retouch** the tutorial portrait step by step.",
     "**Apply** the same tools to one of your own portraits.",
     "**Blink test:** your partner looks at before and after for two seconds each. Can they spot the edits?",
     "**Dial back** anything that looks fake."],
 disc="When does retouching become dishonest?",
 refl="Stoplight on retouching. Then: what's wrong with the planted image?",
 track="SkillsUSA K9: a 20-minute timed retouch with the over-manipulation check."),

dict(n="5.2", title="Content-Aware Fill & Healing", st="EDIT", ex=["EX26"],
 acp=["5.1.a", "5.2.a"], comp=["K9"],
 source="Existing: Didact Content-Aware Fill. Light edit: adds the Spot Healing Brush, Healing Brush, Patch, Clone Stamp, and the newer Remove tool, all named in ACP 5.2.a.",
 drive=["Lesson05 Content Aware Fill (Didact)"],
 di_note="\"I Do\": Content-Aware Fill workspace, Spot Healing, Healing, Patch, Clone Stamp, Remove tool",
 gp_note="\"We Do\": remove five distractions from a practice photo, each with a different tool",
 target="remove distractions with Content-Aware Fill, Spot Healing, Patch, Clone Stamp, and Remove by cleaning up five marked areas",
 org="Five numbered distractions on the practice photo, each with a suggested tool.",
 conn="Uses 2.4's selections as the input to Content-Aware Fill.",
 collab="Think-Pair-Share: should a news photographer ever remove an object from a photo?",
 evid="Glow & Grow exit ticket plus a before/after.",
 summ="Glow & Grow.",
 binder=[], files=[("your cleaned-up photo", "Project Files")], plus="all five fixes are invisible and done on a separate layer", minus="repeating patterns or smudges show",
 iep="Three distractions instead of five; tool pre-assigned.",
 ell="Tool cards with before/after thumbnails.",
 gt="Remove a person from a crowd scene and rebuild the background.",
 mats=["Photoshop", "Lesson05 Content Aware Fill files"],
 notes="Planted error: a clone-stamp repeat pattern.",
 intro="Today you'll learn to make distractions disappear.",
 di="**Spot Healing** fixes small spots automatically. **Healing Brush** and **Clone Stamp** copy from a source you choose (Option-click). **Patch** drags a selection to a clean area. **Content-Aware Fill** fills a selection using the surroundings. The **Remove** tool brushes over objects to erase them. Work on a new layer with 'Sample All Layers' on.",
 cue="See the repeating bricks? That's a clone giveaway. Change the source often.",
 q=("Which tool needs an Option-click source?", "Why would Content-Aware Fill fail on a busy, patterned area?", "Is removing an object okay in a news photo? A contest photo? An ad?"),
 gp=["**Fix the five distractions**, each with its suggested tool.",
     "**Work on a blank layer** with Sample All Layers checked.",
     "**Turn and Talk:** which tool was fastest? Which was cleanest?",
     "**Try one fix** on your own photo."],
 disc="Should TSA or SkillsUSA judges know which objects you removed? Why?",
 refl="Glow and Grow on today's repairs.",
 track="TSA: log every removal in your 'edits made' notes."),

dict(n="5.3", title="Blur & Depth of Field", st="EDIT", ex=["EX22", "EX25"],
 acp=["1.3.c", "3.3.a", "5.1.a", "5.4.a"], comp=["K10"],
 source="Existing: Didact Blur and Depth of Field, merged. Light edit: both are now done as Smart Filters on a Smart Object, which teaches nondestructive editing (ACP 1.3.c) directly.",
 drive=["Lesson05 Blur (Didact)", "Lesson05 Depth of Field (Didact)"],
 di_note="\"I Do\": destructive vs nondestructive, Convert to Smart Object, Blur Gallery (Field, Iris, Tilt-Shift), Lens Blur, filter masks",
 gp_note="\"We Do\": add depth of field and motion blur as Smart Filters, then edit them after the fact",
 target="apply blur and depth-of-field effects as editable Smart Filters, and explain destructive vs nondestructive editing",
 org="Side-by-side demo: same filter applied destructively and as a Smart Filter.",
 conn="Recreates 1.3's in-camera depth of field in software.",
 collab="Partners swap files and change each other's Smart Filter settings to prove they're editable.",
 evid="Emoji meter with a planted-error item.",
 summ="Emoji meter.",
 binder=[], files=[("your Smart Filter .psd", "Project Files")], plus="filters are Smart Filters with masks used to limit them", minus="filters applied directly to pixels",
 iep="Step card: convert, filter, mask.",
 ell="Visual comparison: destructive (permanent) vs nondestructive (editable).",
 gt="Create a convincing tilt-shift 'miniature' from a campus photo.",
 mats=["Photoshop", "Lesson05 Blur and Depth of Field files"],
 notes="Planted error: an obvious halo where a blur mask missed the subject edge.",
 intro="Blur directs the eye. Today you'll add it in Photoshop, in a way you can change later.",
 di="A **destructive** edit changes pixels permanently. A **nondestructive** edit can be changed or removed. Convert a layer to a **Smart Object**, and every filter becomes a **Smart Filter** you can reopen, with a mask to control where it applies. The **Blur Gallery** has Field, Iris, and Tilt-Shift blurs.",
 cue="Double-click the filter name. I can still change the blur amount, even after saving and closing.",
 q=("What's a Smart Filter?", "Why is nondestructive editing safer for a client project?", "When should you blur in camera instead of in Photoshop?"),
 gp=["**Convert** the photo to a Smart Object.",
     "**Add Iris Blur** to fake shallow depth of field; mask the subject.",
     "**Add Path or Motion Blur** to a second image.",
     "**Swap files** with your partner and change their blur amounts."],
 disc="Which is more honest: blur in camera or blur in Photoshop?",
 refl="Emoji meter on Smart Filters. Then: what went wrong in the planted image?",
 track="SkillsUSA troubleshooting card: halos, unintentional blur, and camera shake vs motion blur."),

dict(n="5.4", title="Distortion & Perspective", st="EDIT", ex=["EX24", "EX27"],
 acp=["5.3.a", "5.3.b", "5.4.a"], comp=["K10"],
 source="Existing: Didact Image Distortion and Perspective, merged. Light edit: adds Perspective Crop (ACP 5.3.a) and the Lens Correction filter for converging lines.",
 drive=["Lesson05 Image Distortion (Didact)", "Lesson05 Perspective (Didact)"],
 di_note="\"I Do\": Free Transform modes (skew, distort, perspective, warp), Perspective Warp, Perspective Crop, Lens Correction",
 gp_note="\"We Do\": straighten a building, then place a sign on a wall in perspective",
 target="correct perspective and lens distortion and transform a layer to match a surface",
 org="A transform-mode reference card.",
 conn="Extends 2.3's Free Transform and 3.2's Straighten.",
 collab="Partners judge each other's 'sign on a wall' for realism.",
 evid="3-2-1 with a planted-error image.",
 summ="3-2-1.",
 binder=["your transform reference card"], files=[("your perspective fix", "Project Files")], plus="verticals are vertical and the placed sign matches the wall's angle", minus="visible stretching or mismatched perspective",
 iep="Pre-drawn guide lines on the practice file.",
 ell="Diagrams for skew, distort, perspective, warp.",
 gt="Use Vanishing Point to place a pattern on two walls of a building.",
 mats=["Photoshop", "Lesson05 Image Distortion and Perspective files", "Campus building photos"],
 notes="Planted error: a stretched, non-proportional resize.",
 intro="Lenses bend lines. Today you'll straighten them, and bend some on purpose.",
 di="**Free Transform** (⌘T) has modes: **skew**, **distort**, **perspective**, and **warp**. **Perspective Warp** reshapes a photo by defining planes. The **Perspective Crop** tool straightens a shape like a sign shot at an angle. **Lens Correction** fixes barrel distortion and converging verticals.",
 cue="I draw the crop box on the four corners of the sign, press Return, and it's a flat rectangle.",
 q=("What does the Perspective Crop tool do?", "Why do wide-angle lenses cause more distortion?", "How would you place a poster onto a wall photographed at an angle?"),
 gp=["**Straighten a building** with Lens Correction or Perspective Warp.",
     "**Flatten a sign** with Perspective Crop.",
     "**Place a graphic** onto a wall with Distort.",
     "**Partner check:** does it look real?"],
 disc="When is a 'distorted' look a good creative choice?",
 refl="3-2-1 on today's tools, and name the planted error.",
 track="Panorama prep: shoot a test sequence with 30% overlap for S5."),
]
