# Coverage-matrix data: official ACP Photoshop (2025 exam, v26.x) objectives, competition criteria,
# and the existing-lesson inventory.

ACP = [
 ("1", "Working in the Design Industry", [
  ("1.1.a", "Purpose, audience, and audience needs, including accessibility"),
  ("1.1.b", "Project requirements based on intended use"),
  ("1.1.c", "Communicating design plans (sketches, specs, style guides, briefs)"),
  ("1.1.d", "Project management (scope, scope creep, file management, timeline)"),
  ("1.2.a", "Legal and ethical use of third-party content (copyright, CC, fair use, AI-generated content)"),
  ("1.2.b", "Model and location releases"),
  ("1.3.a", "Digital image terminology (resolution, size, file types, pixel, raster, vector, resampling)"),
  ("1.3.b", "Color modes, bit depth, gamut, histogram"),
  ("1.3.c", "Destructive vs nondestructive editing"),
  ("1.4.a", "Design elements and principles (rule of thirds, framing, aspect ratio, depth of field, field of view, white balance)"),
  ("1.4.b", "Typographic hierarchy"),
 ]),
 ("2", "Project Setup and Interface", [
  ("2.1.a", "Document settings"), ("2.1.b", "Document presets"),
  ("2.2.a", "Interface: panels, workspaces"), ("2.2.b", "Preferences"),
  ("2.2.c", "Navigate (Hand, Rotate View, Zoom)"), ("2.2.d", "Rulers, guides, grids"),
  ("2.3.a", "Open/place, embed/link, Camera Raw, linked Smart Objects, package"),
  ("2.4.a", "Color (Color Picker, Eyedropper)"), ("2.4.b", "Gradients"), ("2.4.c", "Swatches and ASE"),
  ("2.5.a", "Brush, style, and pattern libraries"), ("2.5.b", "Libraries and presets management"),
 ]),
 ("3", "Layers, Masks, and Adjustments", [
  ("3.1.a", "Manage layers"), ("3.1.b", "Opacity, fill, blend modes"), ("3.1.c", "Smart Objects"),
  ("3.2.a", "Manage masks"), ("3.2.b", "Pixel masks, Select and Mask"), ("3.2.c", "Frame tool"),
  ("3.2.d", "Vector masks"), ("3.2.e", "Clipping masks, Paste Into"),
  ("3.3.a", "Adjustments vs adjustment layers, Adjustment Brush, Smart Filters"), ("3.3.b", "Adjustment presets"),
 ]),
 ("4", "Adding Content to a Document", [
  ("4.1.a", "Brush, Pencil, Smudge, Sharpen, Blur, Paint Bucket"),
  ("4.1.b", "Eraser family, Remove Background, History Brush"),
  ("4.1.c", "Generative AI prompts, Sky Replacement"),
  ("4.2.a", "Pen and shape tools"),
  ("4.3.a", "Type tools (Type on a Path, Warp Text, Check Spelling)"), ("4.3.b", "Character and Paragraph"),
  ("4.3.c", "Rasterize or convert type"),
 ]),
 ("5", "Modifying Visual Elements", [
  ("5.1.a", "Selection tools (incl. Select Subject/Object/Sky, Selection Brush, Color Range)"),
  ("5.1.b", "Refine selections"), ("5.1.c", "Save/load selections, channels"),
  ("5.2.a", "Healing, Clone, Content-Aware, Remove, Patch, AI fill"), ("5.2.b", "Burn, Dodge, Sponge"),
  ("5.3.a", "Crop, Perspective Crop, Straighten, resample"), ("5.3.b", "Transforms"),
  ("5.4.a", "Filters vs Smart Filters"), ("5.4.b", "Layer styles"), ("5.4.c", "Materials"),
 ]),
 ("6", "Publishing Digital Media", [
  ("6.1.a", "Export layers and artboards"), ("6.1.b", "Quick Export, Export As"),
  ("6.2.a", "Save: native format, cloud documents"), ("6.2.b", "Formats, bit depth, color space, transparency"),
 ]),
]

COMP = [
 ("TSA Photographic Technology (HS)", [
  ("T1", "Theme interpretation and theme summary"), ("T2", "Required image: color"),
  ("T3", "Required image: black and white"), ("T4", "Required image: macro"),
  ("T5", "Required image: still life"), ("T6", "Required image: student choice"),
  ("T7", "Image statements (camera, f-stop, exposure, ISO, focal length, theme fit, edits)"),
  ("T8", "Composites include unaltered source images"), ("T9", "Portfolio PDF assembly in required order"),
  ("T10", "Student Copyright Checklist and consent/release forms"),
  ("T11", "Technical quality (focus, exposure, white balance, tonal range, lighting)"),
  ("T12", "Design/composition/creativity, impact and theme"),
  ("T13", "Semifinal 24-hr shoot (product, green screen, macro, portrait, still life; tripod, off-camera flash)"),
  ("T14", "Semifinal presentation and interview"), ("T15", "No generative AI (honor statement)"),
 ]),
 ("SkillsUSA Photography", [
  ("K1", "Written test: quality of light"), ("K2", "Written test: DSLR features and functions"),
  ("K3", "Written test: photo basics and digital imaging"), ("K4", "On-location theme assignment"),
  ("K5", "Contact sheet"), ("K6", "Studio portrait with lighting patterns"),
  ("K7", "Light meter; main/fill stop difference"), ("K8", "Composited digital fine-art piece"),
  ("K9", "Photoshop editing task (avoid over-manipulation)"), ("K10", "Troubleshooting common photo errors"),
  ("K11", "Prints: 11×14 mounted on 16×20 with black mat"), ("K12", "Résumé and job interview"),
 ]),
]

# id: (title, periods, coverage {objective: 2 = primary, 1 = partial})
EX = {
 "EX01": ("Welcome Back Graphic", "1", {"2.1.a": 2, "2.2.a": 2, "3.1.a": 1, "4.3.a": 1, "6.1.b": 1}),
 "EX02": ("Intro to Digital Photography (edex + Photography Basics)", "2", {"1.3.a": 2, "1.4.a": 1, "K1": 1, "K2": 2, "K3": 2}),
 "EX03": ("Manual Photography (CameraSim)", "1", {"1.4.a": 1, "K2": 2, "K3": 1, "T11": 1}),
 "EX04": ("About Me", "2–3", {"1.1.a": 1, "2.3.a": 2, "3.1.a": 2, "3.1.b": 1, "4.3.a": 1}),
 "EX05": ("Portrait Photography", "2", {"1.4.a": 2, "K4": 1, "K6": 1, "T6": 1, "T12": 1}),
 "EX06": ("Planning your Shoot", "1", {"1.1.a": 1, "1.1.d": 1, "K4": 1}),
 "EX07": ("Framing", "1", {"1.4.a": 2, "T12": 1}),
 "EX08": ("Focal Length / Sensor / Crop Factor", "1", {"1.4.a": 2, "K2": 2}),
 "EX09": ("Composition", "1", {"1.4.a": 2, "K4": 1, "T12": 2}),
 "EX10": ("Craft the Cutline", "1", {"1.1.a": 1, "T7": 1}),
 "EX11": ("Event Photography", "2–3", {"2.3.a": 1, "K4": 2, "T12": 1}),
 "EX12": ("Photo Cropping", "1", {"1.4.a": 1, "5.3.a": 2}),
 "EX13": ("Photo Usage Rights + Photo Search Skills", "1", {"1.2.a": 2, "T8": 1, "T10": 1}),
 "EX14": ("What Makes a Good News Photo", "1", {"1.4.a": 1, "T12": 1}),
 "EX15": ("Teacher/Staff Profile (journalism)", "4–5", {"1.1.a": 1}),
 "EX16": ("Double Exposure", "1–2", {"3.1.b": 2, "3.2.a": 1, "3.2.b": 1, "K8": 1}),
 "EX17": ("Lighting", "1", {"1.4.a": 1, "K1": 2, "T11": 1}),
 "EX18": ("Shaping Light", "1", {"K1": 1, "K6": 2}),
 "EX19": ("Mood Shoot: Light & Shadow", "2", {"K6": 1, "T3": 1, "T11": 1, "T12": 1}),
 "EX20": ("Ansel Adams", "1", {"1.3.b": 1, "T3": 2, "T12": 1}),
 "EX21": ("RedEye / Brighten / Liquify", "1", {"3.3.a": 1, "5.2.a": 1, "5.3.b": 1, "K9": 1}),
 "EX22": ("Blur", "1", {"4.1.a": 1, "5.4.a": 2}),
 "EX23": ("Panorama + Panorama Assignment", "2", {"2.3.a": 1, "5.2.a": 1, "5.3.b": 1, "T6": 1}),
 "EX24": ("Image Distortion", "1", {"5.3.b": 2, "5.4.a": 1}),
 "EX25": ("Depth of Field", "1", {"1.4.a": 1, "5.1.a": 1, "5.4.a": 1}),
 "EX26": ("Content-Aware Fill", "1", {"5.1.a": 1, "5.2.a": 2, "K9": 1}),
 "EX27": ("Perspective", "1", {"5.3.a": 1, "5.3.b": 2}),
 "EX28": ("Masks & Channels", "1–2", {"3.2.a": 2, "3.2.b": 2, "5.1.b": 2, "5.1.c": 2}),
 "EX29": ("Pattern", "1", {"2.5.a": 1, "3.3.a": 1}),
 "EX30": ("Typographic Design 1 & 2", "2", {"1.4.b": 2, "4.3.a": 2, "4.3.b": 2, "4.3.c": 1}),
 "EX31": ("Magazine Cover", "3", {"1.1.b": 1, "1.4.b": 2, "3.2.e": 1, "4.3.b": 1}),
 "EX32": ("Monster Maker", "2", {"3.1.c": 2, "3.2.a": 1, "5.3.b": 2, "K8": 1}),
 "EX33": ("Text-ure", "1", {"3.2.e": 2, "4.3.a": 1, "5.4.b": 2}),
 "EX34": ("Advanced Compositing Background", "1–2", {"3.1.b": 1, "3.2.a": 1, "3.3.a": 2, "K8": 2}),
 "EX35": ("Delaware Utopia", "3", {"1.1.b": 1, "3.1.c": 1, "K8": 2, "T8": 1}),
 "EX36": ("Mixer Basics", "1", {"2.5.a": 1, "4.1.a": 2}),
 "EX37": ("Painting", "1", {"2.4.a": 1, "2.5.a": 1, "4.1.a": 2}),
 "EX38": ("Photoshop Impressionism", "1", {"4.1.b": 1, "5.4.a": 1}),
 "EX39": ("Google Doodle", "2–3", {"1.1.a": 1, "1.4.a": 1, "3.1.a": 1, "4.3.a": 1}),
 "EX40": ("Layer Basics", "1", {"3.1.a": 2, "3.1.b": 1, "4.3.a": 1, "5.3.b": 1}),
 "EX41": ("Resolution & Image Size", "1", {"1.3.a": 2, "2.1.a": 1, "5.3.a": 1, "6.2.b": 1}),
 "EX42": ("Web Safe Design", "1", {"1.1.a": 2, "6.1.b": 1, "6.2.b": 1}),
 "EX43": ("Light Painting (outline only)", "1–2", {"K2": 1, "T6": 1, "T11": 1}),
 "EX44": ("Magnum Opus TSA Portfolio (outline)", "3+", {"T1": 2, "T2": 1, "T3": 1, "T6": 1, "T7": 1, "T9": 1, "T12": 1}),
 "EX45": ("Cumulative Google Sites Portfolio", "ongoing", {"1.1.a": 1, "6.1.b": 1}),
}

# Where each EX lands in the revision ("cut" items are moved to Units 11-12).
EX_PLACEMENT = {
 "EX01": "2.2", "EX02": "1.1", "EX03": "1.2", "EX04": "S2", "EX05": "S1", "EX06": "3.1", "EX07": "3.1",
 "EX08": "1.3", "EX09": "1.4", "EX10": "3.4", "EX11": "S3", "EX12": "3.2", "EX13": "3.3", "EX14": "3.1",
 "EX15": "Unit 11 (moved out of the ACP window)", "EX16": "6.2", "EX17": "4.1", "EX18": "4.2", "EX19": "S4",
 "EX20": "4.3", "EX21": "5.1", "EX22": "5.3", "EX23": "S5", "EX24": "5.4", "EX25": "5.3", "EX26": "5.2",
 "EX27": "5.4", "EX28": "6.1", "EX29": "6.3", "EX30": "6.4", "EX31": "S6", "EX32": "7.1", "EX33": "7.2",
 "EX34": "7.3", "EX35": "S7", "EX36": "8.1", "EX37": "8.2", "EX38": "8.2", "EX39": "S8", "EX40": "2.3",
 "EX41": "3.2", "EX42": "9.2", "EX43": "8.3", "EX44": "S9", "EX45": "9.2 / S9",
}
