# Fuller wording for fields drafted too tersely in the data files. Applied by gen.py.
P = {
 "5.4": dict(org="A transform-mode reference card (skew, distort, perspective, warp, Perspective Crop) with a thumbnail of each, kept beside the keyboard."),
 "6.1": dict(collab="Step-checking partners: one reads the tutorial step aloud, the other checks the screen; swap at each checkpoint.",
             iep="Tutorial chunked into three checkpoints, with a teacher check at each before moving on."),
 "6.3": dict(ell="Labeled diagrams of the Swatches, Gradients, and Patterns panels, with each control named in English and the home language."),
 "6.4": dict(conn="Prepares directly for S6's magazine cover: today's hierarchy diagram becomes the cover's cover-line plan."),
 "7.1": dict(collab="Step-checking partners: one reads the tutorial step, the other checks the screen; swap at each body part.",
             iep="Tutorial chunked by body part, with a checkpoint screenshot to match at each one.",
             ell="Visual step cards showing each Puppet Warp pin placement."),
 "7.2": dict(org="A layer-style recipe card lists the exact styles and settings for one sample title, so students can rebuild it before inventing their own.",
             conn="Reuses 6.2's clipping mask, now with type as the base layer instead of a portrait.",
             iep="Recipe card with exact settings for every style.", ell="Layer style names paired with thumbnails of what each does.",
             gt="Build a reusable style set (three styles) for a hypothetical photo-studio client and save it to a Library."),
 "7.3": dict(iep="Believability checklist with photo examples of each giveaway (wrong light, mismatched color, missing shadow).",
             ell="Visual believability checklist with an icon for each check.",
             gt="Add a cast shadow and a reflection that match the background's light source."),
 "8.1": dict(org="A brush-settings reference card (size, hardness, flow, wet, load, mix) with a sample stroke for each.",
             collab="Step-checking partners: one reads the tutorial step, the other checks the screen; swap halfway.",
             iep="Tutorial chunked into three checkpoints.", ell="Brush-setting picture card showing a stroke at low and high values.",
             gt="Create and share a custom brush preset, and explain each setting you changed."),
 "8.2": dict(conn="Uses 8.1's brushes and brush presets on a student photo instead of a tutorial file.",
             iep="Plan card with exact filter and brush settings for each step."),
 "8.3": dict(conn="Unit 1's shutter speed, pushed from fractions of a second to whole seconds.",
             iep="Camera pre-set by the teacher (M, ISO 100, f/8, 15 s); student only frames and triggers.",
             ell="Role cards with pictures (camera, painter, timer)."),
 "8.4": dict(conn="Prepares S8's Google Doodle, which needs at least one vector element.",
             iep="Practice sheet with dots marking where each anchor point goes.", ell="Anchor point and handle diagram, labeled.",
             gt="Draw a complex logo shape with the Pen tool using as few anchor points as possible."),
 "9.1": dict(org="A one-page project plan template: client, purpose, audience, deliverables, scope limits, timeline, file-naming plan.",
             conn="Starts S9: the portfolio is the project, and the student is both designer and client.",
             collab="Client/designer role-play in pairs, with a scripted scope-creep request the 'designer' must handle.",
             iep="Template with a completed example beside it.", ell="Meeting sentence frames ('Can you tell me more about…', 'That's outside the scope, so…').",
             gt="Write a short change-order policy a freelance photographer could give clients."),
 "9.2": dict(org="A web export checklist: format, sRGB, long edge in pixels, file size, alt text.",
             conn="Feeds S9's web portfolio page directly.", iep="Checklist with screenshots of each export setting.",
             ell="Alt-text sentence frame: '[Who] [does what] [where].'"),
 "9.3": dict(org="An export decision chart: use → format → color space → bit depth.",
             conn="Pulls together every unit's saving habits into one delivery workflow.",
             iep="Decision chart with a worked example for each use.", ell="Format icons paired with their uses (web, print, transparency, archive).",
             gt="Write a one-page export spec for a client that needs both print and social versions."),
 "9.4": dict(org="A spec sheet for both competitions: SkillsUSA print and mount sizes, TSA PDF order and statement format.",
             conn="The final preparation step before S9's portfolio assembly.",
             iep="Worked mat-math example beside each practice problem.", ell="Spec sheet with labeled diagrams of the mat and the PDF order."),
 "S2": dict(conn="Uses every Unit 2 skill on one project: document presets (2.2), layers (2.3), and selections (2.4).",
            evid="The saved .psd with named, grouped layers and an exported JPEG, submitted to the portfolio.",
            iep="Template with placeholder layers already named and grouped.", ell="Sentence frames for writing the five facts."),
 "S3": dict(org="The 3.1 shot list doubles as the shoot checklist; students check off each shot type as they get it.",
            conn="Uses every Unit 3 skill: planning, cropping and resolution, releases, and cutlines.",
            iep="Three images instead of five, with the cutline frame.", ell="Cutline sentence frame from 3.4.",
            gt="Add a 150-word story to run with the package."),
 "S4": dict(conn="Uses every Unit 4 skill: quality of light, studio patterns, black and white, and still life or macro.",
            collab="Studio teams of three rotate photographer, subject, and light roles; each frame gets one peer note before editing.",
            evid="Three edited images, each with a lighting diagram, submitted to the portfolio.",
            summ="Reflection: what mood does each frame create, and what light choice made it?",
            iep="Two frames instead of three.", ell="Mood vocabulary bank (dramatic, calm, mysterious, warm) with example photos.",
            gt="Light one frame with two lights at a measured 3:1 ratio."),
 "S5": dict(conn="Uses every Unit 5 tool: healing and Content-Aware Fill for the edges, transforms for alignment, Smart Filters if needed.",
            collab="Partners spot each other while shooting on campus and check overlap on the LCD before moving on.",
            evid="The finished panorama (.psd with repair layers) and a repair log listing each fix and the tool used.",
            summ="Reflection: which repair was hardest, and how would you shoot differently to avoid it?",
            iep="Provide a pre-shot overlapping sequence to merge instead of shooting one.", ell="Shoot checklist with pictures.",
            gt="Shoot a vertical or 360° panorama."),
 "S6": dict(org="A cover anatomy diagram (masthead, cover lines, main image, barcode, date line) guides the layout before Photoshop opens.",
            conn="Uses every Unit 6 skill: masks for the masthead, gradients and swatches for color, and 6.4's type hierarchy.",
            collab="Midpoint peer critique: partners read the cover for five seconds and say what they read first, second, and third.",
            evid="The cover .psd with live type and a masked masthead, plus an exported JPEG.",
            summ="Reflection: does the reading order on your cover match what you planned? What would you change?",
            iep="Cover template with masthead and cover-line placeholders.", ell="Headline sentence frames and a cover-line word bank.",
            gt="Design a matching inside spread using the same photo shoot."),
 "S7": dict(conn="Uses every Unit 7 skill: Smart Objects, layer styles, matched light and color, and the AI ethics line.",
            collab="Peer believability check with the 7.3 checklist at the midpoint.",
            evid="The composite .psd, an exported image, and the source-image sheet with every original.",
            summ="Artist statement: what does your utopia say about Delaware, and how did you make the sources belong together?",
            iep="Four sources minimum instead of six; source sheet template provided.", ell="Artist statement sentence frame.",
            gt="Print the composite to SkillsUSA's 11×14 spec."),
 "S8": dict(org="A brief (person or event to celebrate, audience, date) and a pencil sketch come before Photoshop opens.",
            conn="Uses every Unit 8 skill: painting, brushes, and vector shapes from 8.4.",
            collab="Midpoint peer critique: can a classmate tell who or what is being celebrated without being told?",
            evid="The Doodle .psd and a short statement explaining the subject and the design choices.",
            summ="Reflection: which element (painted, photographic, vector) carries the idea most, and why?",
            iep="Doodle template with the letterforms already placed.", ell="Statement sentence frames.",
            gt="Animate one frame of the Doodle as a short GIF."),
 "S9": dict(org="TSA's portfolio checklist, in the required order, is the project's structure.",
            conn="Draws from every unit: each required image category was first shot in Units 1–8.",
            collab="Peer review of image statements against the TSA statement requirements before final assembly.",
            evid="The portfolio PDF (title page, contents, theme summary, five images, statements, references) and a portfolio web page.",
            summ="A two-minute presentation of one image: settings, edits, and how it fits the theme.",
            iep="Checklist chunked into one section per day of the S9 block.", ell="Statement sentence frames and a settings vocabulary bank.",
            gt="Complete the full TSA submission package, including releases and the copyright checklist."),
}
