# PDD revision summatives S1-S9. All are existing projects (none NEW).
SUMMATIVES = [
dict(n="S1", unit=1, title="Portrait Photography", st="EDIT", ex=["EX05"],
 acp=["1.1.a", "1.4.a"], comp=["K4", "K6", "T6", "T7"],
 source="Existing: Portrait Photography project. Light edit: adds a settings log (camera, f-stop, shutter, ISO, focal length) for every submitted frame, the same five fields TSA statements require.",
 drive=["Portraits (exemplar folder)"],
 purpose="Unit 1 has no Photoshop and no GMetrix, so the whole period is shooting and selecting. Students apply 1.1–1.4 to one subject: three portraits (environmental, close-up, and a free choice), each with the settings logged.",
 demo="Teacher shows three exemplar portraits and the settings log",
 work="Pairs shoot each other: environmental, close-up, free choice",
 target="photograph three portraits in manual mode that apply exposure, depth of field, and composition on purpose, and log the settings for each",
 org="A three-shot checklist and the settings log structure the shoot.",
 conn="Directly reuses every Unit 1 skill: manual exposure, focal length and depth of field, and composition.",
 collab="Partners take turns as photographer and subject, and give one composition note per shot.",
 evid="Three portraits plus a completed settings log.",
 summ="Reflection: which portrait best shows a Unit 1 skill, and which skill?",
 binder=["your settings log"], files=[("your three portraits", "Photos")],
 iep="Two portraits instead of three; settings log with check-boxes.",
 ell="Settings log with picture labels; sentence frames for the reflection.",
 gt="Add a fourth portrait lit only by window light, with a note on direction and quality.",
 mats=["DSLRs", "Settings log", "Portrait exemplars"],
 deliver=["**Environmental portrait**: the subject in a place that says something about them.",
          "**Close-up portrait**: shallow depth of field, eyes sharp.",
          "**Free choice**: any technique from 1.4.",
          "**Settings log** for all three (camera, f-stop, shutter speed, ISO, focal length)."],
 track="Tag your best frame as a TSA student-choice candidate."),

dict(n="S2", unit=2, title="About Me", st="EX", ex=["EX04"],
 acp=["1.1.a", "2.3.a", "3.1.a", "3.1.b", "4.3.a", "6.2.a"], comp=["K9"],
 source="Existing: About Me graphic (exemplar PSDs in Drive). Unchanged; reordered to close the Photoshop Foundations unit.",
 drive=["About Me (exemplar PSDs)"],
 purpose="About Me pulls together Unit 2's habits: a correctly set-up document, named and grouped layers, and clean selections, around the student's own photos.",
 demo="Teacher shows an exemplar About Me file with its Layers panel open",
 work="Independent build of the About Me graphic",
 target="design an About Me graphic using a saved preset, organized layers, placed images, clean selections, and live type",
 org="A planning sheet (five things about me, the photo for each, a sketch) comes before Photoshop opens.",
 conn="Uses every Unit 2 skill on one project.",
 collab="Midpoint peer check: partners check the Layers panel for names and groups.",
 evid="The .psd and an exported JPEG.",
 summ="Reflection on which Unit 2 skill was hardest to apply.",
 binder=["your planning sheet"], files=[("your About Me .psd", "Project Files"), ("your exported JPEG", "Exports")],
 iep="Template with placeholder layers.", ell="Sentence frames for the five facts.", gt="Add a double-exposure element or custom brush.",
 mats=["Photoshop", "About Me exemplars", "Students' Unit 1 photos"],
 deliver=["**Five facts** about you, each with an image.", "**Selections** used to isolate at least two images.", "**Named, grouped layers.**", "**Live type** with a clear hierarchy.", "**Saved PSD and exported JPEG.**"],
 track="SkillsUSA K9: after submitting, a timed one-hour edit of a Unit 1 portrait."),

dict(n="S3", unit=3, title="Event Photojournalism Package", st="EDIT", ex=["EX11"],
 acp=["1.4.a", "2.3.a", "5.3.a"], comp=["K4", "K5", "K10", "T2", "T7"],
 source="Existing: Event Photography project. Light edit: Camera Raw (or Bridge) replaces Lightroom, which isn't assumed on the lab Macs, and a contact sheet is added (SkillsUSA K5).",
 drive=["Event Photography"],
 purpose="Students cover the event they planned in 3.1, then select, edit, caption, and deliver a five-image package.",
 demo="Teacher demos Camera Raw basics and making a contact sheet",
 work="Select, edit in Camera Raw, crop, caption",
 target="cover an event and deliver five edited, captioned images plus a contact sheet",
 org="The 3.1 shot list is the checklist.", conn="Uses every Unit 3 skill.",
 collab="Editor-and-photographer pairs choose the final five together.",
 evid="Five images, five cutlines, and a contact sheet.",
 summ="Reflection: which frame tells the story best, and why?",
 binder=["your shot list", "your cutlines"], files=[("your five edited images", "Photos"), ("your contact sheet", "Exports")],
 iep="Three images instead of five.", ell="Cutline sentence frame.", gt="Add a 150-word story.",
 mats=["DSLRs", "Photoshop with Camera Raw", "Release forms"],
 deliver=["**Contact sheet** of the whole shoot.", "**Five edited images** covering the shot types.", "**Five cutlines.**", "**Releases** for any recognizable subject in a promotional use."],
 track="SkillsUSA K4: a 45-minute timed theme shoot as practice."),

dict(n="S4", unit=4, title="Mood Shoot: Light & Shadow", st="EDIT", ex=["EX19"],
 acp=["1.4.a", "3.3.a"], comp=["K6", "K11", "T3", "T4", "T5"],
 source="Existing: Mood Shoot Light & Shadow. Light edit: the three required frames now line up with TSA categories (B&W, still life or macro, lit portrait), and a print-mounting extension is added for the competition track.",
 drive=["Mood Shoot Light & Shadow"],
 purpose="A shoot built around light and mood, finishing before winter break so every student has a first pass at TSA's B&W, still life, and macro categories and the SkillsUSA lighting patterns.",
 demo="Teacher shows mood exemplars and lighting diagrams",
 work="Shoot and edit three mood frames",
 target="create three mood images (B&W, still life or macro, and a portrait with a named lighting pattern) that use light and shadow on purpose",
 org="A shot plan with a lighting diagram per frame.", conn="Uses every Unit 4 skill.",
 collab="Studio teams rotate roles.",
 evid="Three edited images with lighting diagrams.",
 summ="Reflection on the mood each frame creates.",
 binder=["your lighting diagrams"], files=[("your three mood images", "Photos")],
 iep="Two frames instead of three.", ell="Mood vocabulary bank.", gt="Use two lights with a measured ratio.",
 mats=["DSLRs", "Speedlites and triggers", "Still-life props", "Tripods"],
 deliver=["**Black-and-white** frame (adjustment layer, not mode change).", "**Still life or macro.**", "**Portrait** with a named lighting pattern.", "**Lighting diagram** for each."],
 track="Mount one print to SkillsUSA spec."),

dict(n="S5", unit=5, title="Original Panorama", st="EX", ex=["EX23"],
 acp=["2.3.a", "5.2.a", "5.3.b", "6.2.a"], comp=["T6", "T11"],
 source="Existing: Panorama (Didact Lesson05) + the own-photo Panorama Assignment. Unchanged.",
 drive=["Lesson05 Panorama (Didact)", "Panorama Assignment"],
 purpose="Students shoot an original campus panorama, merge it with Photomerge, and repair the edges with Unit 5's tools. The S5 block also runs through winter break (Dec 14 – Jan 4), so the competition-track checkpoint lives here.",
 demo="Teacher demos Photomerge and edge repair",
 work="Shoot, merge, repair, and finish the panorama",
 target="shoot and merge an original panorama and repair its edges with Content-Aware Fill and healing tools",
 org="Shoot checklist (overlap, exposure lock, tripod).", conn="Uses every Unit 5 tool.",
 collab="Partners spot each other on campus.",
 evid="The finished panorama and a repair log.",
 summ="Reflection on which repair was hardest.",
 binder=["your repair log"], files=[("your panorama", "Project Files")],
 iep="Provide a pre-shot sequence.", ell="Checklist with pictures.", gt="Shoot a vertical or 360° panorama.",
 mats=["DSLRs", "Tripods", "Photoshop"],
 deliver=["**Original sequence** with 25–40% overlap.", "**Merged panorama** (Photomerge).", "**Repaired edges** on separate layers.", "**Repair log.**"],
 track="TSA draft portfolio checkpoint: choose five category candidates and draft one statement; SkillsUSA résumé draft."),

dict(n="S6", unit=6, title="Magazine Cover", st="EX", ex=["EX31"],
 acp=["1.1.b", "1.4.b", "3.2.e", "4.3.b"], comp=["K9"],
 source="Existing: Magazine Cover (exemplar folder). Unchanged.",
 drive=["Magazine Cover (exemplars)"],
 purpose="A cover built around the student's own photo, applying masks and type.",
 demo="Teacher deconstructs a real cover's hierarchy",
 work="Shoot or choose the cover photo, build the cover",
 target="design a magazine cover around their own photo with a masked masthead and a clear typographic hierarchy",
 org="Cover anatomy diagram.", conn="Uses every Unit 6 skill.",
 collab="Peer critique on hierarchy.",
 evid="The cover PSD and export.",
 summ="Reflection on hierarchy.",
 binder=["your cover sketch"], files=[("your cover .psd", "Project Files"), ("your cover export", "Exports")],
 iep="Template.", ell="Headline frames.", gt="Design a matching inside spread.",
 mats=["Photoshop", "Magazine exemplars"],
 deliver=["**Original cover photo.**", "**Masthead** partly behind the subject (mask).", "**Hierarchy** of headline, cover lines, and details.", "**Trim and bleed** set correctly."],
 track=""),

dict(n="S7", unit=7, title="Delaware Utopia", st="EDIT", ex=["EX35"],
 acp=["1.1.b", "3.1.c", "3.2.b", "3.3.a"], comp=["K8", "T8"],
 source="Existing: Delaware Utopia. Light edit: adds a source-image sheet (every source, unaltered) for TSA and SkillsUSA composite rules.",
 drive=["Delaware Utopia"],
 purpose="A composited fine-art piece imagining an ideal Delaware, from student-shot sources where possible.",
 demo="Teacher shows the believability checklist on an exemplar",
 work="Build the composite",
 target="create a believable composite from multiple sources and document every source",
 org="Source-image sheet and believability checklist.", conn="Uses every Unit 7 skill.",
 collab="Peer believability check.",
 evid="Composite and source sheet.",
 summ="Artist statement.",
 binder=["your source sheet"], files=[("your composite .psd", "Project Files")],
 iep="Fewer sources.", ell="Statement frame.", gt="Print for SkillsUSA.",
 mats=["Photoshop", "Student and licensed sources"],
 deliver=["**Composite** from at least four sources.", "**Source-image sheet** with every original unaltered.", "**Artist statement.**", "**No generative AI** if this will be a TSA entry."],
 track="SkillsUSA K8: print the composite."),

dict(n="S8", unit=8, title="Google Doodle", st="EX", ex=["EX39"],
 acp=["1.1.a", "1.1.b", "3.1.a", "4.2.a", "4.3.a"], comp=[],
 source="Existing: Google Doodle (exemplar PSD). Unchanged.",
 drive=["Google Doodle.psd"],
 purpose="A Doodle celebrating a person or event, combining painting, photos, and vector shapes.",
 demo="Teacher shows past Doodles",
 work="Build the Doodle",
 target="design a Google Doodle that combines painted, photographic, and vector elements for a specific audience",
 org="Brief and sketch.", conn="Uses every Unit 8 skill.",
 collab="Peer critique.", evid="Doodle and statement.", summ="Reflection.",
 binder=["your sketch"], files=[("your Doodle .psd", "Project Files")],
 iep="Template.", ell="Frames.", gt="Animate a frame.",
 mats=["Photoshop", "Google Doodle exemplar"],
 deliver=["**Google letters** readable.", "**Painted element.**", "**Vector element.**", "**Statement.**"],
 track=""),

dict(n="S9", unit=9, title="Magnum Opus Photography Portfolio", st="EDIT", ex=["EX44", "EX45"],
 acp=["1.1.a", "1.1.d", "6.1.b", "6.2.b"], comp=["T1", "T2", "T3", "T4", "T5", "T6", "T7", "T9", "T10", "T12", "T14", "K11", "K12"],
 source="Existing: Magnum Opus TSA Photography Portfolio (2023 outline) and the cumulative Google Sites portfolio. Light edit: rebuilt to TSA's current format (5 images: color, B&W, macro, still life, student choice) as the core for everyone.",
 drive=[],
 purpose="The capstone. Every student curates and delivers a five-image portfolio in TSA's format with a web page; competition-track students add the full submission package.",
 demo="Teacher shows the TSA order and a sample portfolio",
 work="Curate, edit, write statements, assemble",
 target="curate and present a five-image photography portfolio with statements in TSA's format",
 org="TSA checklist.", conn="Draws from every unit.",
 collab="Peer review of statements.",
 evid="Portfolio PDF and web page.",
 summ="Presentation reflection.",
 binder=["your TSA checklist"], files=[("your portfolio PDF", "Exports")],
 iep="Checklist chunked by section.", ell="Statement frames.", gt="Full TSA submission.",
 mats=["Photoshop", "Google Sites", "TSA guide"],
 deliver=["**Five images**: color, B&W, macro, still life, student choice.", "**Statements** for each.", "**Theme summary.**", "**References.**", "**Web page.**"],
 track="TSA submission; two mounted SkillsUSA prints; résumé; mock interview."),
]
