# Unit-level data for the PDD revision draft.
DRIVE_MAIN = "https://drive.google.com/drive/folders/1EhTaO-SZa8VImaH5UzXeNF_t4qTXFFO2"
DRIVE_DIDACT = "https://drive.google.com/drive/folders/1rRIOzZql6hj4yAHwKtoEsi2SpFgxlNmF"

UNITS = [
 dict(n=1, title="Camera Fundamentals & Exposure", dates="Sep 1 – Sep 23, 2026", days=10, periods="5 (plus the Sep 1–3 icebreaker)",
  desc="The DSLR in manual mode: exposure triangle, focal length and crop factor, depth of field, and composition, ending in a portrait shoot with a settings log.",
  intro="Unit 1 puts a camera in every student's hands before Photoshop opens. Students learn to take control of exposure, lens, and composition in manual mode, and start the habit the whole year depends on: logging the settings behind every frame. That log becomes the metadata in their TSA statements and the vocabulary of the SkillsUSA written test.",
  outcomes=["Explain how aperture, shutter speed, and ISO each change exposure and the look of a photo",
            "Set a DSLR to manual mode and correct an over- or underexposed frame",
            "Predict how focal length, crop factor, and aperture change field of view and depth of field",
            "Apply rule of thirds, framing, leading lines, and viewpoint on purpose"],
  acp="1.3.a (digital image terms), 1.4.a (rule of thirds, framing, aspect ratio, depth of field, field of view)",
  comp="SkillsUSA K1–K3 (written test: photo basics, DSLR functions), K4 (on-location shooting), K6 (portrait, introduced); TSA T6 (student-choice image), T7 (settings log for statements), T11 (exposure and focus)",
  existing="EX02 Intro to Digital Photography, EX03 Manual Photography (CameraSim), EX08 Focal Length/Crop Factor, EX09 Composition, EX05 Portrait Photography",
  assess="F1–F4 exit tickets (rotating); F5 cumulative vocab quiz; F6 stinger grade; S1 Portrait Photography with a settings log",
  core="Every student shoots, logs settings, and turns in three portraits (S1).",
  track="Competition-track students start a running SkillsUSA written-test flashcard deck (K1–K3) and tag one S1 frame as a possible TSA student-choice image.",
  literacy="Frayer-model cards for aperture, shutter speed, ISO, and depth of field; reading the camera's own menu labels as technical text.",
  numeracy="Shutter fractions (1/60 vs 1/250), one stop = double or half the light, f-number sequence, crop factor: 50 mm × 1.6 ≈ 80 mm equivalent.",
  gm="No GMetrix/BrainBuffet this unit. The lab setup and ACP pre-test happen in 2.1, the same pattern as FDD and ADD."),
 dict(n=2, title="Photoshop Foundations", dates="Sep 24 – Oct 12, 2026", days=13, periods="6.5",
  desc="GMetrix setup and ACP pre-test, the Photoshop workspace and documents, layers, and selections, ending in the About Me graphic.",
  intro="Unit 2 moves from the camera to Photoshop. It opens with the GMetrix setup and ACP pre-test day (the same 2.1 FDD and ADD run), then builds the three habits every later unit assumes: setting up a document correctly, working in named layers, and making a clean selection.",
  outcomes=["Create a document with the right size, resolution, and color mode for its use, and save a preset",
            "Navigate and customize the workspace (Hand, Zoom, Rotate View, rulers, guides, preferences)",
            "Create, name, group, and reorder layers, and set opacity, fill, and blend mode",
            "Choose the right selection tool for a subject and refine the edge"],
  acp="2.1.a–b, 2.2.a–d, 3.1.a–b, 5.1.a–b, 2.3.a (place/embed), 4.3.a (intro), 6.2.a (save PSD)",
  comp="SkillsUSA K9 (Photoshop editing task, introduced)",
  existing="EX01 Welcome Back Graphic, EX40 Layer Basics, EX04 About Me",
  assess="Custom 2.1 pre-test exit ticket; F2–F4; F5; F6; S2 About Me graphic",
  core="Everyone: pre-test, workspace, layers, selections, About Me.",
  track="A timed 'one-hour edit' drill on one of their Unit 1 portraits (SkillsUSA K9 format) during S2 time once About Me is submitted.",
  literacy="Reading procedural tutorial text (Classroom in a Book steps) with a step-checking partner.",
  numeracy="Pixel dimensions = inches × ppi (8 in × 300 ppi = 2400 px); document size presets compared.",
  gm="2.1: GMetrix setup + ACP pre-test. 2.2–2.4: BrainBuffet Photoshop Module 1 (Crash Course), ~1.5 h of its ~6 h."),
 dict(n=3, title="Photojournalism", dates="Oct 13 – Oct 30, 2026", days=13, periods="6.5",
  desc="Planning a shoot, framing the news photo, cropping and resolution, usage rights and releases, and cutlines, ending in an event photojournalism package.",
  intro="Unit 3 sends students out to cover a real school event. It pairs the oldest photo genre with the most-tested ACP ideas in Domain 1: who owns an image, when you need a release, and what resolution and size a photo needs for its use. The cutline lesson also starts the written statements TSA requires for every portfolio image.",
  outcomes=["Plan a shoot around purpose, audience, and a shot list",
            "Crop for impact and set resolution and image size for print or screen",
            "Decide when an image is legal and ethical to use, and when a model or location release is needed",
            "Write an accurate cutline that answers the 5 Ws"],
  acp="1.1.a, 1.1.d (intro), 1.2.a–b, 1.3.a, 1.4.a, 2.1.a, 2.3.a (Camera Raw), 5.3.a, 6.2.b",
  comp="SkillsUSA K4 (on-location assignment), K5 (contact sheet), K10 (troubleshooting); TSA T1 (theme interpretation), T7 (written statements), T8/T10 (copyright checklist, releases)",
  existing="EX06 Planning your Shoot, EX07 Framing, EX14 What Makes a Good News Photo, EX12 Photo Cropping, EX41 Resolution & Image Size, EX13 Photo Usage Rights, EX10 Craft the Cutline, EX11 Event Photography",
  assess="F1–F4; F5; F6; S3 Event Photojournalism Package (5 edited images + cutlines + contact sheet)",
  core="Everyone covers one event, builds a contact sheet, and turns in five captioned images.",
  track="Practice a 45-minute timed on-location theme assignment (SkillsUSA K4) and draft one TSA-style image statement from an S3 frame.",
  literacy="Cutlines (5 Ws), reading Creative Commons license terms and a release form closely.",
  numeracy="Resolution math (px ÷ ppi = inches), aspect ratios (3:2 camera vs 4:5 Instagram vs 16:9), crop percentages.",
  gm="BrainBuffet Photoshop Module 1 (Crash Course), continued: ~2 h."),
 dict(n=4, title="Light & Art Photography", dates="Nov 4 – Dec 1, 2026", days=14, periods="7",
  desc="Quality of light, studio lighting patterns with off-camera flash, black-and-white and the histogram, and still life and macro, ending in a light-and-shadow mood shoot.",
  intro="Unit 4 is the lighting unit, placed before Christmas on purpose: it gives every student a rudimentary pass at the skills both competitions judge most (studio lighting patterns and off-camera flash for SkillsUSA; black and white, macro, and still life for TSA's required image categories) before the winter break.",
  outcomes=["Describe light by its quality, direction, and color, and set white balance to match",
            "Set up and name the basic portrait lighting patterns with an off-camera flash",
            "Convert an image to black and white with an adjustment layer and read its histogram",
            "Light and shoot a still life and a macro subject"],
  acp="1.3.b (color modes, bit depth, histogram), 1.4.a (white balance, depth of field), 3.3.a–b (adjustment layers and presets)",
  comp="SkillsUSA K1 (quality of light), K6 (studio lighting patterns), K7 (light meter, main/fill ratio), K11 (print mounting, competition track); TSA T3 (B&W), T4 (macro), T5 (still life), T13 (off-camera flash, product shots)",
  existing="EX17 Lighting, EX18 Shaping Light, EX20 Ansel Adams, EX19 Mood Shoot: Light & Shadow",
  assess="F1–F4; F5; F6; S4 Mood Shoot (3 images: one B&W, one still life or macro, one portrait with a named lighting pattern)",
  core="Everyone shoots one B&W, one still life or macro, and one lit portrait.",
  track="Mount one print to SkillsUSA spec (11×14 on 16×20 board with mat) and log a main/fill ratio with the light meter.",
  literacy="Short reading on Ansel Adams and the Zone System; lighting-pattern names as a picture vocabulary bank.",
  numeracy="Lighting ratios in stops (main f/8 + fill f/5.6 = 1 stop = 2:1), inverse-square falloff (double the distance, ¼ the light), the histogram as a data distribution.",
  gm="BrainBuffet Photoshop Module 1 (Crash Course), finish: ~2 h. Module 1 should be complete by S4."),
 dict(n=5, title="Image Correction", dates="Dec 2, 2026 – Jan 4, 2027", days=14, periods="7",
  desc="Retouching and repair: red eye, dodge/burn/sponge, Liquify, Content-Aware Fill and healing, blur and depth of field, distortion and perspective, ending in an original panorama.",
  intro="Unit 5 teaches students to fix photos: the retouching and repair tools that fill the SkillsUSA Photoshop task and a large share of ACP Domain 5. Every exit ticket this unit includes one planted photo error to diagnose, building the SkillsUSA troubleshooting skill a little at a time.",
  outcomes=["Retouch a portrait with healing, red eye, Dodge/Burn/Sponge, and Liquify without over-editing",
            "Remove distractions with Content-Aware Fill, Remove, Patch, and Clone Stamp",
            "Apply blur and depth-of-field effects as Smart Filters",
            "Correct perspective and distortion, and merge a panorama"],
  acp="1.3.c (nondestructive editing), 3.3.a (Smart Filters), 5.1.a, 5.2.a–b, 5.3.a–b, 5.4.a, 6.2.a",
  comp="SkillsUSA K9 (Photoshop task, avoid over-manipulation), K10 (troubleshooting); TSA T6 (student choice), T11 (technical quality)",
  existing="EX21 RedEye/Brighten/Liquify, EX26 Content-Aware Fill, EX22 Blur, EX25 Depth of Field, EX24 Image Distortion, EX27 Perspective, EX23 Panorama",
  assess="F1–F4 (each with a planted-error item); F5; F6; S5 Original Panorama",
  core="Everyone retouches, repairs, and turns in an original panorama shot on campus.",
  track="During the S5 block (Dec 14 – Jan 4): TSA draft portfolio checkpoint (5 categories chosen, one statement drafted) and a SkillsUSA résumé draft.",
  literacy="Procedural text: students write their own 4-step 'how I fixed it' note for each repair (it becomes TSA's 'edits made' line).",
  numeracy="Degrees in the Straighten and Rotate tools; percent overlap (25–40%) between panorama frames.",
  gm="BrainBuffet Photoshop Module 2 (Retouch or Real), ~2 h."),
 dict(n=6, title="Masks, Channels & Type", dates="Jan 5 – Jan 22, 2027", days=13, periods="6.5",
  desc="Layer masks, Select and Mask, channels, double exposure, patterns, gradients and swatches, and typographic design, ending in a magazine cover.",
  intro="Unit 6 is the nondestructive core of Photoshop: masks instead of erasers, saved selections in channels, and type that stays live. It ends with a magazine cover, which puts a student photograph under a real typographic hierarchy.",
  outcomes=["Hide and reveal with layer masks, refine edges in Select and Mask, and save selections to channels",
            "Blend two photos into a double exposure with masks, blend modes, and clipping masks",
            "Build and save gradients, swatches, and patterns",
            "Set type with a clear hierarchy using the Character and Paragraph panels"],
  acp="1.4.b, 2.4.a–c, 2.5.a–b, 3.1.b, 3.2.a–b, 3.2.e, 4.3.a–c, 5.1.b–c, 1.1.b",
  comp="SkillsUSA K8 (composite, introduced), K9",
  existing="EX28 Masks & Channels, EX16 Double Exposure, EX29 Pattern, EX30 Typographic Design 1 & 2, EX31 Magazine Cover",
  assess="F1–F4; F5; F6; S6 Magazine Cover",
  core="Everyone masks, builds a double exposure, and designs a cover around their own photo.",
  track="Re-edit one TSA candidate image with masks only (no erasing) and log the edits for its statement.",
  literacy="Headline and deck writing for the cover; type vocabulary (kerning, tracking, leading) with picture cards.",
  numeracy="Point size and leading (12 pt type on 14.4 pt leading = 120%), trim size + 0.125 in bleed on each side.",
  gm="BrainBuffet Photoshop Module 3 (Cinematic Landscape), ~2 h."),
 dict(n=7, title="Advanced Compositing", dates="Feb 1 – Feb 23, 2027", days=15, periods="7.5",
  desc="Smart Objects and Puppet Warp, layer styles and materials, compositing backgrounds, and generative AI tools and their ethics, ending in a composited fine-art piece.",
  intro="Unit 7 is the composite unit: building a believable image from several sources. It is the SkillsUSA fine-art composite, and it is also where students meet Photoshop's generative AI tools, which the ACP exam tests and TSA's honor statement bans. Students learn both the tools and where the line is.",
  outcomes=["Transform Smart Objects nondestructively, including Puppet Warp",
            "Apply and edit layer styles and materials",
            "Match light, color, and perspective across composite sources",
            "Use Generative Fill, Remove Background, and Sky Replacement, and explain when they may and may not be used"],
  acp="1.2.a (AI-generated content), 3.1.b–c, 3.2.a–b, 3.2.e, 3.3.a, 4.1.b–c, 5.3.b, 5.4.b–c, 1.1.b",
  comp="SkillsUSA K8 (composited digital fine art); TSA T8 (composite source images), T13 (green-screen style subject swap), T15 (no GenAI in TSA work)",
  existing="EX32 Monster Maker, EX33 Text-ure, EX34 Advanced Compositing Background, EX35 Delaware Utopia",
  assess="F1–F4; F5; F6; S7 Delaware Utopia composite with a source-image sheet",
  core="Everyone builds a composite and documents its sources.",
  track="SkillsUSA-format composite print; for TSA, keep all source frames unaltered for the References page and leave GenAI out entirely.",
  literacy="Short argument paragraph: 'Should AI-generated images be allowed in photo contests?' using the TSA honor statement and Adobe's Content Credentials as sources.",
  numeracy="Scale percentages when matching subject size across sources; vanishing-point alignment.",
  gm="BrainBuffet Photoshop Module 4 (Movie Poster), ~2 of its ~3.5 h."),
 dict(n=8, title="Digital Painting & Vector", dates="Feb 24 – Mar 17, 2027", days=15, periods="7.5",
  desc="Mixer Brush, painting and Impressionism effects, light painting, and vector shapes, the Pen tool, frames, and vector masks, ending in a Google Doodle.",
  intro="Unit 8 covers the brush engine and Photoshop's vector side. It adds light painting, a long-exposure technique that's a strong student-choice portfolio image, and closes the last ACP gaps in Domains 3 and 4 (Pen and shape tools, the Frame tool, and vector masks).",
  outcomes=["Paint with the Mixer Brush and custom brush settings",
            "Turn a photo into a painterly image with brushes, the History Brush, and filters",
            "Plan and shoot a long-exposure light painting",
            "Draw with the Pen and shape tools, and mask with frames and vector masks"],
  acp="1.4.a, 2.4.a, 2.5.a, 3.1.a, 3.2.c–d, 4.1.a–b, 4.2.a, 4.3.a, 5.4.a, 1.1.a–b",
  comp="SkillsUSA K2 (shutter control), K10; TSA T6 (student choice), T11",
  existing="EX36 Mixer Basics, EX37 Painting, EX38 Photoshop Impressionism, EX43 Light Painting, EX39 Google Doodle",
  assess="F1–F4; F5; F6; S8 Google Doodle",
  core="Everyone paints, shoots one light painting, and builds a Doodle with vector elements.",
  track="Refine the light painting as a TSA student-choice candidate with a complete settings statement.",
  literacy="Short reading on Impressionism; artist statement for the Doodle.",
  numeracy="Long-exposure seconds and the reciprocal rule; anchor points as coordinates.",
  gm="BrainBuffet Photoshop Module 4 finish (~1.5 h) and Module 5 (Generative AI) start (~0.5 h)."),
 dict(n=9, title="Publishing, Delivery & Portfolio", dates="Mar 18 – Apr 16, 2027", days=15, periods="7.5",
  desc="Client communication and project management, web-ready portfolios and accessibility, saving and exporting, and print presentation, ending in the Magnum Opus photography portfolio.",
  intro="Unit 9 closes the ACP content and assembles the year's work. Students learn the client-side and delivery objectives (briefs, scope, export formats, file management), then curate the Magnum Opus: a five-image portfolio in TSA's format that every student completes, with print mounting and the interview as competition-track extensions.",
  outcomes=["Read a brief, write a project plan, and manage scope and files",
            "Export images for web and print with the right format, color space, and bit depth",
            "Prepare a portfolio page that meets accessibility basics (alt text, contrast)",
            "Present a curated portfolio and explain each image's settings and edits"],
  acp="1.1.a–d, 1.3.c, 2.2.b, 2.3.a (link/package), 6.1.a–b, 6.2.a–b",
  comp="TSA T1–T12, T14 (presentation and interview); SkillsUSA K11 (mounted prints), K12 (résumé and interview)",
  existing="EX42 Web Safe Design, EX45 Cumulative Google Sites portfolio, EX44 Magnum Opus TSA Photography Portfolio",
  assess="F1–F4; F5; F6; S9 Magnum Opus Photography Portfolio",
  core="Everyone builds the 5-image TSA-format portfolio PDF and a portfolio web page.",
  track="TSA submission package (copyright checklist, releases, references), two mounted SkillsUSA prints, résumé, and a mock interview.",
  literacy="Design briefs, image statements, résumé and cover letter; interview practice with sentence frames.",
  numeracy="11×14 at 300 ppi = 3300 × 4200 px; mat-window math (16×20 board, 11×14 window, borders); file-size budgets for web.",
  gm="BrainBuffet Photoshop Module 5 finish (~1.5 h) and Module 6 (Echo Hart client project) start; Module 8 (exam prep) is assigned as homework from S9 on."),
]
