# BrainBuffet module data for the FMLA FDD (Illustrator) and FMLA ADD (Premiere Pro) units.
# Video IDs, lengths and titles come from BrainBuffet's 2025 teacher lesson plans (Drive).
# Vocabulary is drawn from each module's glossary, reworded for students.

def v(s):
    """'1.01 8:18 Getting Started' -> (id, seconds, 'm:ss', title)"""
    vid, length, title = s.split(" ", 2)
    m, sec = length.split(":")
    return (vid, int(m) * 60 + int(sec), f"{int(m)}:{sec}", title)

AI = {
 1: dict(name="Getting Started with Illustrator", short="Getting Started",
  product="your 25 Dog logo and your own animal built from basic shapes, saved as an .ai file and a PDF",
  product_title="Your Own Animal",
  overview="Module 1 tours Illustrator from the ground up: documents, the workspace, shapes, color, type, the Direct Selection tool, and saving. It ends with you building an animal of your own from basic shapes.",
  videos=[v(x) for x in [
   "1.01 8:18 Getting Started", "1.02 8:45 Navigating the Interface",
   "1.03 7:32 Selection Tool, Rectangle Tool, and Rasters vs. Vectors", "1.04 4:42 Stroke Weights and Zooming",
   "1.05 9:17 Rounded Rectangles and Corner Widgets", "1.06 8:22 Ellipses and Polygons",
   "1.07 9:13 Save Your Work and Make Cool Stars", "1.08 9:02 Adding Artboards and Area Type",
   "1.09 6:12 Point Type", "1.10 10:04 Area Type Tool and Type on a Path Tool",
   "1.11 8:44 The Touch Type Tool", "1.12 5:06 Create Outlines and the Direct Selection Tool",
   "1.13 7:34 Pathfinder and Handles", "1.14 6:57 Views, Line Segment, and Expand Shapes",
   "1.15 8:22 One Handle at a Time", "1.16 10:50 The Quickest Bear There Ever Was",
   "1.17 5:44 Make Your Own Animal and Save as a PDF"]],
  acp="1.4, 2.1, 2.2, 2.3, 2.5, 4.1, 4.2, 4.3, 4.4, 4.6, 5.2",
  worksheet="the **Module 1 Worksheet** (an Illustrator practice file: draw shapes, reshape them, set and reshape type, then design one graphic of your own) and the **Keyboard Shortcuts note catcher**",
  worksheet_note="The practice file is an Illustrator template (.ait), so Illustrator makes you **File › Save As** a copy. If Illustrator asks to activate fonts, choose **Activate**. The guides inside the file only show up in Illustrator, not in a Drive preview.",
  worksheet_grade="BrainBuffet's worksheet rubric: every practice task completed, and every keyboard shortcut filled in on the note catcher.",
  ext="Look up \"animals made out of numbers\" and build a second number animal, the same way the 25 Dog is built from a 2 and a 5.",
  rubric="50 pts (BrainBuffet's Module 1 project rubric, halved): Mastery of Skills 40 (Selection tool, basic shapes, point vs. area type, saving, plus an original animal), Effort 5 (all artboards and tasks done), Requirements 5 (on time, saved as a PDF; −1 per day late).", points=50,
  vocab=[("Anchor Point", "A point on a path that controls the path's shape and direction, shown as a small square."),
         ("Area Type", "Type that flows inside a shape or text box and wraps to the next line at the box's edge."),
         ("Artboard", "The page-like canvas you design on in Illustrator. One document can hold several artboards."),
         ("Fill", "The color, gradient or pattern inside a shape."),
         ("Handles", "The lines that stick out of a selected anchor point on a curve. Dragging their round ends changes the curve."),
         ("Landscape Orientation", "A layout that is wider than it is tall."),
         ("Pixel", "One tiny square of color in the grid that makes up a raster image."),
         ("Point Type", "A single line of type that starts where you click and keeps going until you press Return."),
         ("Portrait Orientation", "A layout that is taller than it is wide."),
         ("Raster (Bitmap)", "An image made of a fixed grid of pixels. It gets blurry or blocky when enlarged."),
         ("Stroke", "The outline along a shape's path. Its thickness is the stroke weight."),
         ("Swatches", "Saved colors, gradients or patterns in the Swatches panel, ready to reuse."),
         ("Vector", "Artwork built from mathematical paths, so it can be scaled to any size without losing quality.")],
  ),
 2: dict(name="Dobson National Park Branding Style Guide", short="Branding Style Guide",
  product="the Dobson National Park Branding Style Guide, saved as a PDF",
  product_title="Dobson National Park Branding Style Guide",
  overview="Module 2 introduces the running client, Dobson National Park. You build its branding style guide: color codes (HSB, RGB, CMYK, HEX), swatches, type classifications, visual hierarchy, logo usage and logo no-gos.",
  videos=[v(x) for x in [
   "2.01 6:04 What are Branding Guidelines?", "2.02 4:03 A Familiar Company's Style Guide",
   "2.03 3:37 Client Brief", "2.04 4:13 Scope Creep and Document Setup",
   "2.05 5:29 Workspace and Rearranging Artboards", "2.06 5:48 Organizing our Document",
   "2.07 7:11 HSB", "2.08 7:23 RGB vs. CMYK and Additive vs. Subtractive",
   "2.09 5:24 Don't Be Out of Gamut!", "2.10 2:29 More New Swatches!", "2.11 5:54 Create Swatch Info",
   "2.12 3:20 Rename Swatches", "2.13 2:11 Swatch Info for Our Color Scheme",
   "2.14 7:09 Type Classifications, Sans Serif vs. Serif", "2.15 9:11 More Type Classifications!",
   "2.16 6:52 Titles/Headings, Subtitles, Body Copy, and Special Text", "2.17 8:46 Visual Hierarchy",
   "2.18 8:16 Bringing in the 25 Dog!", "2.19 2:37 Organizing Our Logo Usage",
   "2.20 3:54 Preparing to Reorganize with Visual Elements", "2.21 3:57 My Design Elements",
   "2.22 5:06 Logo No-Gos", "2.23 4:04 Done! But… Not Forever! Revise as Needed!"]],
  acp="1.1, 1.2.b, 1.4, 1.5, 2.1, 2.2, 2.4, 2.5, 4.1, 4.2, 4.3, 4.4, 5.2",
  worksheet="the **Module 2 Worksheet** (make five color swatches with swatch info cards, then activate a font for each type classification and type its name in that font) and the **Module 2 Note Catcher**",
  worksheet_note="If Illustrator asks to activate fonts, choose **Activate**. You'll need Module 1's 25 Dog in this module too; BrainBuffet includes a finished copy if yours is missing.",
  worksheet_grade="BrainBuffet's worksheet rubric: 5 swatch info cards (1 pt each), 8 type classifications (1 pt each), and the note catcher answered.",
  ext="Make a branding style guide for yourself as if you were a famous designer, athlete or artist: your logo, color scheme, fonts and design elements.",
  rubric="50 pts (BrainBuffet's Module 2 project rubric, halved): Mastery of Skills 40 (document setup, rearranged artboards, swatches with exact color codes, type choices, logo usage and no-gos, design elements), Effort 5, Requirements 5 (on time, saved as a PDF; −1 per day late).", points=50,
  vocab=[("Additive Color", "Color made by adding light. Red, green and blue light added together make white (RGB)."),
         ("Branding Style Guide", "A document that sets the rules for how a brand looks: logos, colors, fonts and design elements."),
         ("Client Brief", "A document that explains a project's goals, target audience and deliverables."),
         ("CMYK", "Cyan, magenta, yellow and black (key): the four ink colors used in printing."),
         ("Color Gamut", "The range of colors a device or color mode can reproduce. A color outside it is out of gamut."),
         ("HEX", "A six-character code (#RRGGBB) that names a color for the web."),
         ("HSB", "Hue, saturation and brightness: a way to describe a color by its pigment, intensity and lightness."),
         ("Logo", "A symbol or design an organization uses to identify itself."),
         ("Non-Objective Visual Elements", "Shapes, lines, colors and textures that don't picture anything real. They keep a brand consistent and attractive."),
         ("RGB", "Red, green and blue: the colors of light a screen uses to display images."),
         ("Sans Serif", "A typeface without the small strokes (serifs) at the ends of letters. Common on screens, signs and logos."),
         ("Scope Creep", "When a project grows beyond what was planned and agreed to."),
         ("Serif", "A typeface with small strokes at the ends of letters. Common in printed body text."),
         ("Subtractive Color", "Color made by ink absorbing light. Cyan, magenta and yellow inks combine toward black (CMYK)."),
         ("Visual Hierarchy", "Arranging elements so the viewer's eye moves through them in order of importance."),
         ("Wordmark", "A logo made only of text, like \"Dobson National Park.\"")],
  ),
 3: dict(name="Dobson National Park Poster", short="National Park Poster",
  product="the Dobson National Park poster, built on organized layers and saved as a PDF",
  product_title="Dobson National Park Poster",
  overview="Module 3 uses your style guide to design a national park poster. It introduces the Layers panel, plus gradients, effects, the Pen tool, symbols, brushes, patterns, opacity and blending modes.",
  videos=[v(x) for x in [
   "3.01 3:52 Client Brief", "3.02 6:07 Document Set Up", "3.03 5:55 Libraries", "3.04 6:30 Gradients",
   "3.05 8:37 Moon Effects and Mountains", "3.06 4:59 Foreground Mountains and the Knife Tool",
   "3.07 8:12 Pen Tool Hills", "3.08 5:22 Pie Widget Hills", "3.09 7:06 Trees 1",
   "3.10 7:41 Recolor Trees and Add Grass Brush", "3.11 7:02 Reflection", "3.12 6:21 Layer Colors",
   "3.13 4:04 Save Your Work!", "3.14 7:29 Water Gradient and Sublayers", "3.15 5:09 Patterns",
   "3.16 5:15 Opacity and Blending Modes", "3.17 8:52 Snowflake Pattern",
   "3.18 5:33 Visual Elements and Text", "3.19 5:02 Finishing Up"]],
  acp="1.1, 1.2, 1.3, 1.4, 1.5, 2.1, 2.2, 2.3, 2.5, 2.6, 3.1, 3.2, 4.1, 4.2, 4.5, 4.6, 5.2",
  worksheet="the **Module 3 Worksheet** (6 symbols, 6 brushes, 6 effects, 6 patterns, 3 gradients and 3 blending modes)",
  worksheet_note="Keep your Module 2 style guide open: the poster has to follow your own branding rules.",
  worksheet_grade="BrainBuffet's worksheet rubric: 30 items (1 pt each): 6 symbols, 6 brushes, 6 effects, 6 patterns, 3 gradients, 3 blending modes.",
  ext="Add Dobson's 25 hiking trails to your poster (trails on the mountains or a trailhead sign), or design a second vector poster of your hometown.",
  rubric="50 pts (BrainBuffet's Module 3 project rubric, halved): Mastery of Skills 40 (poster matches the style guide; symbols, brushes, gradients, patterns and blending modes; layers managed), Effort 5 (all required layers), Requirements 5 (on time, saved as a PDF; −1 per day late).", points=50,
  vocab=[("Atmospheric Perspective", "Showing depth by making faraway objects paler, less detailed and bluer than close ones."),
         ("Blending Mode", "A setting that controls how a layer's colors mix with the colors beneath it."),
         ("Brush", "A preset that applies a decorative style along a path, like grass or a painted stroke."),
         ("Copyright", "The creator's legal right to control how their work is copied, shared and used."),
         ("Copyright Infringement", "Using a copyrighted work without the owner's permission."),
         ("Gradient", "A gradual blend between colors. Illustrator has linear, radial and freeform gradients."),
         ("Layer", "A level in the Layers panel that holds artwork and controls its stacking order."),
         ("Opacity", "How see-through an object or layer is, from 0% (invisible) to 100% (solid)."),
         ("Pattern", "A tile of artwork that repeats to fill a shape."),
         ("Public Domain", "Work that no one owns the copyright to, so anyone can use it."),
         ("Sublayer", "A layer nested inside another layer, used to organize related artwork."),
         ("Symbol", "A reusable piece of art stored in the Symbols panel. Every copy updates when the original changes.")],
  ),
 4: dict(name="Dobson National Park Trifold", short="Trifold Brochure",
  product="the Dobson National Park trifold brochure (two artboards, printed back to back), saved as a PDF",
  product_title="Dobson National Park Trifold Brochure",
  overview="Module 4 designs a two-sided trifold brochure for Dobson. It covers model release forms, copyright and Creative Commons, bleeds and guides, preferences, placing images and text, clipping masks, text wrap and leading.",
  videos=[v(x) for x in [
   "4.00 8:15 Wireframe Explanation", "4.01 5:05 Model Release Form", "4.02 3:12 Create Document",
   "4.03 7:39 Bleeds and Guides", "4.04 7:53 Preferences", "4.05 5:23 Create Our Hierarchy",
   "4.06 7:18 Front Panel: Add Our Logo and Wordmark", "4.07 5:23 Front Panel: Place Our Picture and Create Clipping Mask",
   "4.08 3:09 Front Panel: Radial Gradient", "4.09 8:30 Place Text and Spell Check",
   "4.10 7:21 Creative Commons: Introduction", "4.11 9:28 Creative Commons: Worksheet",
   "4.12 8:45 Add Some Images", "4.13 6:14 Text Wrapping and Hyphenation",
   "4.14 8:05 Pictures, Clipping Masks, and Captions", "4.15 4:55 Place Text and Leading",
   "4.16 5:10 Rearranging Our Text", "4.17 8:12 Foliage and Pictures", "4.18 7:32 The LAST Panel!",
   "4.19 2:48 The Last Three Pictures", "4.20 6:14 Wrap It Up and Save!", "4.21 5:38 The Trifold"]],
  acp="1.1, 1.2.b, 1.3.a, 1.3.b, 1.5, 2.1.a, 2.2.c, 2.3.d, 2.4.b, 2.5, 3.2.b, 4.2.e, 4.3.b",
  worksheet="the **Creative Commons Worksheet** (build the five Creative Commons license symbols with shapes and Pathfinder, and label each with its initials). Video 4.11 walks through it step by step",
  worksheet_note="If you haven't reached video 4.11 yet, watch 4.10 and 4.11 now: they introduce Creative Commons and walk through this worksheet.",
  worksheet_grade="BrainBuffet's worksheet rubric: 5 Creative Commons symbols (2 pts each) and the correct initials on each (1 pt each).",
  ext="Fold a sheet of paper into a mini zine (search \"mini zine\" for the fold) and design one in Illustrator about a topic you choose.",
  rubric="BrainBuffet Module 4 project rubric (100 pts): Mastery of Skills 80 (readable, well-formatted trifold; can explain model releases, copyright and Creative Commons, bleeds, preferences, clipping masks, text wrap, linked images), Effort 10 (all panels with client text and images), Requirements 10 (on time, saved as a PDF; −2 per day late).", points=100,
  vocab=[("Bleed", "Artwork that extends past the trim edge so the printed piece has no white slivers after cutting."),
         ("Clipping Mask", "A shape that hides everything outside it, like a window. The hidden artwork isn't deleted."),
         ("Copyright", "The creator's legal right to control how their work is copied, shared and used."),
         ("Creative Commons", "Licenses that let creators share their work with clear rules, like giving credit or no commercial use."),
         ("Guides", "Non-printing lines you drag out of the rulers to line things up."),
         ("Leading", "The vertical space between lines of type."),
         ("Margin", "The space between the edge of the page and the content."),
         ("Model Release Form", "A signed form giving permission to use a recognizable person's image."),
         ("Nondestructive Edit", "A change that can be undone or adjusted later without losing the original, like a clipping mask instead of a crop."),
         ("Public Domain", "Work that no one owns the copyright to, so anyone can use it (Creative Commons CC0)."),
         ("Text Wrap", "Making type flow around an image or shape instead of running behind it.")],
  ),
}

PR = {
 2: dict(name="Fire Academy Recruiting Video", short="Fire Academy Recruiting Video",
  product="the 60-second Fire Academy recruiting video, exported twice through Media Encoder: one version with burned-in captions and one with a sidecar caption file",
  product_title="Fire Academy Recruiting Video",
  overview="Module 2: Miami Dade College hires you to cut a 60-second recruiting video for its Fire Science Technology Academy. You build a story spine from interviews with text-based editing, add B-roll, music and sound effects, trim with slip, slide and roll edits, and deliver two captioned versions.",
  videos=[v(x) for x in [
   "2.01 3:48 Introduction & Project Planning", "2.02 4:52 Getting Started", "2.03 4:06 Organizing Clips in Bins",
   "2.04 5:57 Sequence Presets & Track Organization", "2.05 4:34 Understanding the Script",
   "2.06 5:17 Auto Scene Detection & Subclips", "2.07 10:41 Adding Edits with the Patch Panel",
   "2.08 11:07 Text-to-Video Editing", "2.09 6:54 Refining the Interview Sequence", "2.10 7:11 Labeling Clips",
   "2.11 9:40 Adding B-Roll with Media Intelligence", "2.12 10:40 Rolling Video & Sound Bridging",
   "2.13 4:44 Slipping & Wiping", "2.14 10:20 Sliding & Replacing Clips", "2.15 10:22 Polishing the Final Sequence",
   "2.16 6:42 Creating Captions", "2.17 9:44 Exporting with Media Encoder"]],
  acp="1.1.a, 1.1.d, 2.1.b, 2.2.a, 2.2.b, 3.1.a, 3.2.a, 4.1.a, 4.3.c, 4.4.b, 4.6.b, 4.7.b, 4.7.c, 5.3.a, 5.3.b",
  ext="Re-edit your recruiting video as a vertical cut for TikTok, Instagram Reels or YouTube Shorts. Think about what grabs attention in the first three seconds.",
  rubric="BrainBuffet Module 2 rubric (100 pts): Mastery 80 (bins/labels 10, sequence settings and tracks 10, ripple/slip/slide/roll edits 20, B-roll and sound bridges 10, titles/captions in safe margins 10, Media Encoder export 10, text-based editing or Patch panel 10), File management 10, On time 10 (−2 per day late).",
  vocab=[("Caption Track", "A timeline track that holds subtitles or closed captions."),
         ("Export", "Saving the finished edit as a video file ready to play or upload."),
         ("Label Colors", "Colors assigned to clips in a bin or the timeline to keep them organized."),
         ("Media Encoder", "A separate Adobe app that queues and exports Premiere Pro sequences in the background."),
         ("Patch Panel", "The track controls at the left of the timeline that decide which tracks receive inserted or overwritten clips."),
         ("Rolling Edit", "Moving an edit point between two clips, so one gets longer and the other shorter by the same amount."),
         ("Scratch Disk", "The setting that decides where Premiere Pro stores previews and captured media."),
         ("Sequence Preset", "Saved sequence settings such as frame size, frame rate and codec."),
         ("Sidecar File", "A separate caption file (like .srt) delivered alongside a video, so viewers can turn captions on or off."),
         ("Slide Edit", "Moving a clip along the timeline while the clips on either side adjust, so the sequence length stays the same."),
         ("Slip Edit", "Changing which part of a clip plays without changing its length or position in the timeline."),
         ("Sound Bridge", "Audio that carries across a cut between two clips (a J-cut or L-cut)."),
         ("Text Panel", "The panel that shows a transcript of the dialogue, so you can edit video by editing text.")],
  handbook="Module 2 Handbook"),
 3: dict(name="Horror Chase Spec Film: No Way Out", short="Horror Chase: No Way Out",
  product="the No Way Out horror chase scene with a 2.40:1 crop, a horror color grade and rolling credits, exported to the festival specs (2048 × 1080, 24 fps, ProRes 422 HQ), with the project archived",
  product_title="No Way Out: Horror Chase Scene",
  overview="Module 3: you edit a horror spec film headed to festivals. You work with proxies and mixed formats, plan in Freeform view, trim with ripple, extract and lift, design sound, crop to 2.40:1, color-grade for horror, and build rolling credits.",
  videos=[v(x) for x in [
   "3.01 3:30 Introduction and Project Planning", "3.02 4:26 Creating Proxies", "3.03 8:26 Understanding & Relinking Proxies",
   "3.04 6:26 Storyboard Editing", "3.05 3:35 Media Scaling & Selection Order", "3.06 6:13 Rendering",
   "3.07 10:28 Ripple Trimming and Extract & Lift", "3.08 6:54 Scaling & Positioning",
   "3.09 8:54 Blending Music & Adding Video Effects", "3.10 6:19 Keyframing & More Video Effects",
   "3.11 11:54 Sound Design", "3.12 4:02 Scene Edit Detection", "3.13 10:37 Splitting Edits",
   "3.14 2:45 Sequence Nesting", "3.15 6:09 Anamorphic Cropping", "3.16 7:49 Color Grading",
   "3.17 12:30 Rolling Credits", "3.18 12:42 Finishing Touches", "3.19 4:47 Exporting"]],
  acp="1.1.b, 1.2.a, 2.2.a, 2.4.a, 3.1.a, 3.2.a, 4.1.a, 4.3.a, 4.3.b, 4.4.a, 4.4.b, 4.4.c, 4.5.a, 4.5.b, 5.1.a, 5.3.a, 5.3.c",
  ext="Cut a 30-second festival trailer for No Way Out from your finished film and title cards.",
  rubric="BrainBuffet Module 3 rubric (100 pts): Storytelling & editing flow 20, Visual effects & animation 20, Sound & music 20, Color & visual style 20, Final details (credits, export settings, polish) 20.",
  vocab=[("Adjustment Layer", "A clip that applies its effects to every clip below it in the timeline."),
         ("Anamorphic Crop", "Cropping the top and bottom of the frame to get a cinematic 2.40:1 look."),
         ("Echo Effect", "A video effect that leaves ghostly motion trails."),
         ("Export Settings", "The format, codec, frame size and frame rate used when you output a video."),
         ("Freeform View", "A Project panel view where you arrange clips by hand, like a storyboard."),
         ("Gain", "The volume level of an audio clip before it reaches the mix."),
         ("Keyframe", "A marker that sets a property's value at one point in time, so it can change over time."),
         ("Nesting", "Putting a sequence inside another sequence so it acts like a single clip."),
         ("Poster Frame", "The thumbnail image that represents a clip in the Project panel."),
         ("Proxy", "A low-resolution copy of a video file that makes editing smoother."),
         ("Render Bar", "The colored bar above the timeline: green is rendered, yellow may play smoothly, red needs rendering."),
         ("Ripple Edit", "A trim that adds or removes time and slides the following clips to close the gap."),
         ("Rolling Credits", "A list of names that scrolls up the screen at the end of a film."),
         ("Scene Edit Detection", "A tool that finds the cuts in a long clip and splits it into separate shots."),
         ("Sync Lock", "A track setting that keeps tracks in sync when you insert or remove time."),
         ("Vignette", "Darkening or lightening the edges of the frame to pull the eye toward the center.")],
  handbook="Module 3 Handbook"),
 4: dict(name="College Basketball Athlete Showreel", short="Athlete Showreel",
  product="the one-minute athlete showreel with animated lower thirds, speed ramps and translated captions, exported in every required format and aspect ratio (including a vertical YouTube Shorts version)",
  product_title="Athlete Showreel",
  overview="Module 4: an athlete needs a one-minute highlight reel for recruiters and sponsors. You start from a project template, build a story arc, add frame holds and speed ramps, animate lower thirds and text, translate captions, and export multiple deliverables.",
  videos=[v(x) for x in [
   "4.01 3:39 Introduction & Project Planning", "4.02 9:00 Project Templates", "4.03 4:20 Story Spine",
   "4.04 6:35 Fleshing It Out", "4.05 13:11 Frame Hold & Scale Animation", "4.06 9:22 Speed Ramping",
   "4.07 8:18 Effect Presets", "4.08 5:15 Markers", "4.09 5:47 Project Manager", "4.10 5:34 Implementing VFX",
   "4.11 8:02 Lower Thirds", "4.12 13:46 Animating Text", "4.13 9:28 Translating Captions",
   "4.14 11:13 Export Specs", "4.15 10:56 Additional Deliverables"]],
  acp="1.1.a, 1.5.a, 2.2.b, 2.3.a, 3.1.c, 3.1.d, 3.1.e, 3.3.a, 3.4.c, 3.4.d, 3.5.b, 3.5.c, 4.1.a, 4.1.b, 4.2.b",
  ext="Make 15–30 second teaser versions of the showreel for TikTok, Instagram Stories or X, keeping the story clear in less time.",
  rubric="BrainBuffet Module 4 rubric (100 pts): Project setup & organization 15, Story arc & clip selection 20, Motion graphics & text 15, Effects & transitions 15, Audio mix & captions 15, Final deliverables 20.",
  vocab=[("B-Roll", "Extra footage that supports the main shots, like cutaways and background action."),
         ("Effect Presets", "Saved effect settings you can reuse for consistent results."),
         ("Frame Hold", "Freezing one frame of a clip for a set time to add emphasis."),
         ("Lower Third", "A graphic in the lower part of the screen that shows a name, title or hashtag."),
         ("Markers", "Notes you place on a clip or the timeline to flag a moment or a range."),
         ("Project Manager", "A tool that collects, copies or trims a project's media into one place."),
         ("Quick Export", "A fast export that uses default or last-used settings."),
         ("Safety Margins", "On-screen guides that show where titles and action won't get cut off on different screens."),
         ("Sequence", "A timeline where you assemble video and audio clips into a finished program."),
         ("Speed Ramping", "Smoothly speeding up or slowing down a clip for a dramatic effect."),
         ("Story Arc", "The order of events that builds interest and delivers a clear story.")],
  handbook="Module 4 Handbook"),
 5: dict(name="Exam Prep & Practice", short="Exam Prep & Practice",
  product="the Grand Finale (video 5.14) exported, plus each mini-challenge practice file completed",
  product_title="Exam Prep Grand Finale",
  overview="Module 5 is short, fast concept videos aimed at ACP exam objectives the projects didn't cover deeply: client questions, shot types, Ultra Key, copyright and releases, PSD import, typography, audio fades, white balance, syncing, blend modes and Warp Stabilizer. It ends with a Grand Finale challenge.",
  videos=[v(x) for x in [
   "5.01 3:53 Introduction", "5.02 1:50 Questions for Clients", "5.03 2:25 Shot Type Showdown!",
   "5.04 2:31 Ultra Key", "5.05 1:04 Copyright & Releases", "5.06 2:06 Importing Photoshop Documents",
   "5.07 2:19 Typography", "5.08 2:12 Audio Fade Out", "5.09 2:20 White Balance", "5.10 2:19 Tool Icon Throwdown!",
   "5.11 3:02 Syncing & Linking", "5.12 3:12 Blend Mode", "5.13 2:49 Warp Stabilizer", "5.14 6:09 The Grand Finale"]],
  acp="1.1.a, 1.3.a, 1.3.b, 1.4.b, 1.5.a, 2.2.a, 2.4.a, 3.1.b, 4.1.a, 4.2.a, 4.2.b, 4.5.b, 4.5.c, 4.5.d, 4.6.a, 4.6.b",
  ext="Design your own ACP-style exam task: pick one objective, write a short scenario and instructions, and test it on a classmate.",
  rubric="BrainBuffet Module 5 rubric (100 pts): Mastery 80 (Horizontal Type and Transform tools, change font, size and color, name layers, group layers), Effort/file naming 10, On time 10 (−2 per day late).",
  vocab=[("Blend Mode", "A setting that controls how one layer's pixels mix with the layers below."),
         ("Chroma Key", "Removing one color (usually green or blue) so another image shows through."),
         ("Drop Shadow", "A shadow behind text or graphics that makes them easier to read."),
         ("Gaussian Blur", "A soft blur that reduces detail and sharpness."),
         ("PSD Import", "Bringing a layered Photoshop file into Premiere Pro."),
         ("Track Matte Key", "An effect that uses one layer as a matte to control where another layer is visible."),
         ("Typography", "Arranging type so it is readable and visually appealing."),
         ("Ultra Key", "Premiere Pro's effect for removing a green or blue screen background."),
         ("Warp Stabilizer", "An effect that analyzes shaky footage and smooths out camera movement."),
         ("White Balance", "Correcting color so white objects look white under any kind of light.")],
  handbook="Module 5 Handbook"),
}

# FMLA unit -> BrainBuffet module (per the teacher's plan)
FDD_UNITS = {3: 1, 4: 2, 5: 3, 6: 4}
ADD_UNITS = {3: 2, 4: 3, 5: 4, 6: 5}
UNIT_DATES = {3: ("Oct 13 – Oct 30, 2026", 13), 4: ("Nov 4 – Dec 1, 2026", 14), 5: ("Dec 2, 2026 – Jan 4, 2027", 14), 6: ("Jan 5 – Jan 22, 2027", 13)}

AI[5] = dict(name="Dobson's Business Card", short="Business Card",
  product="Dobson's business card (front and back), revised from client feedback, with Image-Traced contact icons, outlined text and strokes, saved as a print-ready PDF with trim marks",
  product_title="Dobson's Business Card",
  overview="Module 5 designs a business card for Dobson's park manager. It covers raster vs. vector and JPG vs. PNG, Image Trace, Share for Review and client feedback, printing a sample, outlining text and strokes, and Asset Export.",
  videos=[v(x) for x in [
   "5.01 3:10 Client Brief: Business Card", "5.02 3:26 Don't Reinvent the Business Card Wheel", "5.03 6:32 Document Setup",
   "5.04 6:58 RASTER vs. VECTOR and JPG vs. PNG", "5.05 5:50 Image Trace", "5.06 7:29 More Image Tracing",
   "5.07 3:03 Adding Our Text", "5.08 6:47 Arranging Text and Icons", "5.09 6:10 Adding Imagery", "5.10 7:23 Share for Review",
   "5.11 6:51 Feedback and New Icon", "5.12 6:35 Tackling More Feedback", "5.13 4:35 Rearranging Artboards",
   "5.14 3:06 Back Side of Card", "5.15 1:40 Ask Sam for Feedback", "5.16 4:14 Sam's Feedback", "5.17 5:37 Print a Sample",
   "5.18 3:09 Printed Sample", "5.19 1:46 Email Dobson", "5.20 3:07 Final Approval and Outline Text", "5.21 4:01 Outline Stroke",
   "5.22 7:07 Asset Export", "5.23 7:36 Preparing for Print"]],
  acp="1.1.a–c, 1.2.a, 1.3.a, 2.1.a–b, 2.2.a, 2.3.a, 2.4.b, 3.1.a–c, 4.1.d, 4.2.a, 5.1.a, 5.3.b, 5.4.a",
  worksheet="the **Image Trace Worksheet** (trace each image with the settings the worksheet asks for: presets, Threshold, Ignore Color, then expand)",
  worksheet_note="Rewatch videos 5.05 and 5.06 if you need a refresher on the Image Trace panel.",
  worksheet_grade="BrainBuffet's worksheet rubric: every image traced with the correct settings (2 pts each, 12 pts).",
  ext="Design a business card for a real teacher or coach at school (ask first), using what you learned about hierarchy and bleeds.",
  rubric="50 pts (BrainBuffet's Module 5 project rubric, halved): Mastery of Skills 40 (several card versions plus a final version after feedback, all required info, Image-Traced contact icons, varied layouts and imagery), Effort 5 (feedback questions answered thoughtfully), Requirements 5 (on time, saved as a PDF; −1 per day late).", points=50,
  vocab=[])

AI[6] = dict(name="Generative AI in Adobe Illustrator", short="Generative AI & Exam Tips",
  product="the Generative AI & Mockup worksheet: vectors generated from your own descriptive prompts, plus at least one Mockup, saved as a PDF",
  product_title="Generative AI & Mockup Worksheet",
  overview="Module 6 introduces Illustrator's newest tools: Generate Vectors, Generative Shape Fill, Mockup and Adobe Firefly, plus test-taking tips for the certification exam.",
  videos=[v(x) for x in [
   "6.01 9:58 Getting Started with AI and Prompt Writing Basics", "6.02 8:35 Generate Vectors with Detailed Prompt Writing",
   "6.03 5:04 Gen Shape Fill", "6.04 7:26 Gen Shape Fill plus Mockup", "6.05 5:46 Practice Mockup and Jump into Firefly",
   "6.06 6:19 Creating with Firefly", "6.07 3:56 This is Goodbye… and Good Luck!"]],
  acp="1.3.a, 2.4.b, 4.1.e",
  worksheet="the **Generative AI & Mockup Worksheet** (generate vectors from the worksheet's subjects using your own descriptive prompts, then practice Mockup)",
  worksheet_note="Write your own prompts with descriptive words, colors, lighting, mood and an art style. Don't paste the task instructions in as your prompt. Keep every prompt school-appropriate.",
  worksheet_grade="BrainBuffet's Module 6 rubric (100 pts): Mastery 80 (experimented and created several AI-generated and Mockup graphics), Effort 10 (all worksheet tasks), Requirements 10 (on time, saved as a PDF).",
  ext="Use Mockup to put the school logo on a promotional item, like a water bottle or T-shirt.",
  rubric="", vocab=[])

# ---------------------------------------------------------------- FDD remap: 1.5 modules per unit
# Each graded slot: ("work",) = no graded item; ("vocab", list index); ("stinger", span); ("worksheet", module);
# ("product", module) = a summative due on a formative day; ("summative", module). s_extra = more items due on the last S day.
# Grading schema (FDD): 12 formatives x 10 pts = 120 (6 worksheets, 5 vocab quizzes, 1 stinger check) and
# 300 summative pts (animal 50, style guide 50, poster 50, trifold 100, business card 50).
FORMATIVE_PTS = 10
AI_HOURS = {1: 3, 2: 3, 3: 3, 4: 4, 5: 3, 6: 1}   # BrainBuffet's estimated class time per module
FDD_PLAN = {
 3: dict(start="1.01", end="1.17", title="Illustrator Module 1: Getting Started",
         slots={"F1": ("work",), "F2": ("vocab", 0), "F3": ("work",), "F4": ("worksheet", 1), "S": ("summative", 1)}),
 4: dict(start="2.01", end="3.19", title="Illustrator Modules 2–3: Branding Style Guide & National Park Poster",
         slots={"F1": ("work",), "F2": ("vocab", 0), "F3": ("worksheet", 2), "F4": ("product", 2), "S": ("summative", 3)},
         s_extra=[("worksheet", 3)]),
 5: dict(start="4.00", end="5.06", title="Illustrator Modules 4–5: Trifold & Image Trace",
         slots={"F1": ("vocab", 0), "F2": ("work",), "F3": ("vocab", 1), "F4": ("worksheet", 4), "S": ("summative", 4)}),
 6: dict(start="5.07", end="6.07", title="Illustrator Modules 5–6: Business Card & Generative AI",
         slots={"F1": ("worksheet", 5), "F2": ("work",), "F3": ("stinger", "Units 4–6"), "F4": ("vocab", 0), "S": ("summative", 5)},
         s_extra=[("worksheet", 6)]),
}

_V = {t: d for m in (1, 2, 3, 4) for t, d in AI[m]["vocab"]}
_V.update({
 "Business Card": "A small card with a person's name, job and contact information, used for networking.",
 "Expand": "Turning a traced or styled object into plain, editable vector paths.",
 "Ignore Color": "An Image Trace option that leaves a chosen color (like a white background) out of the trace.",
 "Image Trace": "An Illustrator feature that converts a raster image into vector paths.",
 "JPG": "A raster file format for photos. It does not support transparency.",
 "PNG": "A raster file format that supports transparency.",
 "Threshold": "An Image Trace setting that decides which pixels become black and which become white.",
 "Asset Export": "A panel that exports selected artwork as separate files in several formats and sizes at once.",
 "Create Outlines": "Converting live type into vector shapes so it looks the same on any computer, even without the font.",
 "Outline Stroke": "Converting a stroke into a filled shape so it keeps its thickness when scaled.",
 "Share for Review": "An Illustrator feature that sends a link so others can comment on your design.",
 "Trim Marks": "Small lines printed at the corners that show where to cut the paper.",
 "Adobe Firefly": "Adobe's generative AI app for creating images and effects from text prompts.",
 "Artificial Intelligence (AI)": "Computer systems that perform tasks like learning, problem-solving and recognizing patterns.",
 "Generative AI": "AI that creates new content, such as images or text, from a prompt.",
 "Generate Vectors": "An Illustrator generative AI tool that creates editable vector art from a text prompt.",
 "Generative Shape Fill": "An Illustrator generative AI tool that fills a shape with vector detail from a prompt.",
 "Mockup": "An Illustrator feature that previews flat artwork on a 3D object, like a logo on a mug.",
 "Prompt": "The text description you give generative AI to tell it what to create.",
})
# Vocab lists per unit, in the order the unit's vocab slots use them: (label, terms)
FDD_VOCAB = {
 3: [("Module 1", [t for t, _ in AI[1]["vocab"]])],
 4: [("Module 2", [t for t, _ in AI[2]["vocab"]])],
 5: [("Module 3", [t for t, _ in AI[3]["vocab"]]), ("Module 4", [t for t, _ in AI[4]["vocab"]])],
 6: [("Modules 5–6", ["Business Card", "JPG", "PNG", "Image Trace", "Threshold", "Ignore Color", "Expand", "Share for Review",
                      "Create Outlines", "Outline Stroke", "Asset Export", "Trim Marks", "Artificial Intelligence (AI)", "Generative AI",
                      "Prompt", "Generate Vectors", "Generative Shape Fill", "Mockup", "Adobe Firefly"])],
}
FDD_VOCAB = {u: [(lab, [(t, _V[t]) for t in ts]) for lab, ts in groups] for u, groups in FDD_VOCAB.items()}
